### ISSUE TITLE
Movement Sensor is not identify a move. - binarysensor

### ISSUE THREAD

**Issue by fahhome123** [jheling/freeathome#100]
current firmware 2.6.1

Movement Sensor is not identify a move.
On firmware 2.4.x I had no problem with this.

**Comment by jheling** [comment]
Can you activate the monitoring services as described in the debugging section  and then use the movement sensor. The logging should give us as clue what is going wrong.

**Comment by theripper78** [comment]
Homeassistant is not discovering the movement entity. Only the lux and a "On/Off"-Entity

**Comment by miezie** [comment]
The device_class is not set properly. 

See this: https://www.home-assistant.io/integrations/sensor/
And this: https://www.home-assistant.io/docs/configuration/customizing-devices/#device-class

You can use home assistant customizing entities options to make it work. An improvement for the component would be to set the device classes properly.

**Comment by theripper78** [comment]
Ok, I have customised the entity as a device_class type : move ... But the state is allways "detected".  
I think I have the same issue like "fahhome123" has. I am running on Version 2.6.x.

**Comment by miezie** [comment]
Ah, it is marked as always on. 

Is it an option to use emulated_hue to expose the thing you want to trigger in hass with this sensor? That’s way more stable then the other way around and simply works…

In this way I personally have several template switches and zwave switches which I exposed and trigger with FAH hardware.

**Comment by Tho85** [comment]
Could it be possible that the movement sensor is not attached to any other device in free@home, e.g. lights? Sensors that are not attached to anything do not send updates to the free@home SysAP. This is a limitation of free@home and nothing this component can fix.

If so, the better solution would be like @miezie described: Expose the things you want to control from Home Assistant via `emulated_hue` to free@home, and attach the movement sensor to this new exposed device in free@home.

**Comment by oliverlinsenmaier** [comment]
Same problem here as well. And this gets forwarded to HomeKit as well...

**Comment by theripper78** [comment]
So, I am using emulated_hue in home assistant... I can import my HomeAssistant-Server in Free@Home like a Hue-Bridge easily and configure my movement automation in Free@home to trigger a device configured in HomeAssistant. (i.e. ESP-Device with WLED Image). I am Happy with this.
