### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by henning89** [jheling/freeathome#103]
I recently tried updating to Home Assistant 6.x and this integration did not work anymore afterwards. After going back to 5.x, I discovered the below message in the log file.
Any chance that you can update the code to include a version key @jheling ? 

> ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'freeathome'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'freeathome'

**Comment by jheling** [comment]
Hello,  if you look in the freeathome directory here on github, you will find a manifest.json that allready contains a version key.  If you use this file in your environment the integration should work again.

**Comment by henning89** [comment]
Thanks for the very fast feedback. I'll try it out.
