### ISSUE TITLE
Missing feature: tilt setting of covers

### ISSUE THREAD

**Issue by Tau-Neutrino** [jheling/freeathome#104]
Hi,

first of all: thank you very much for this project! Works super smooth and reliable!

The only feature I am missing is the possibilty to adjust the tilt of the covers.

I played around with the official rest api and found out that the tilt position can be set via writting a value to either 
`ch0003 or ch0006 datapoint idp0003 / pairing ID: 36`
`ch0003` is used for a 1/2 actor while `ch0006` is used for 1/1 actors.

value range in the official api ranges from 
`0 (open lamelas)`  to  `100 (closed lamelas)`

So its bassically the same as for the cover position, wich is set via `idp0002 / pairing ID: 35` on the same channel.

At the moment I am using the offical rest api via curl to set the tilt of the covers, which works good but is of course not the preferred way!

example:
`curl -X PUT "http://192.168.3.9/fhapi/v1/api/rest/datapoint/00000000-0000-0000-0000-000000000000/ABB123456789.ch0006.idp0003" -H  "accept: application/json" -H  "Authorization: Basic AAAAAAAAAAAAAAAAAAA" -H  "Content-Type: text/plain" -d "100"`

Any plans to integrate the tilt position setting in your api?

BR,
Gerald

**Comment by Tho85** [comment]
I've added support for the cover tilt setting in #105, feel free to test the code there and see if it works for you.

**Comment by Tau-Neutrino** [comment]
perfect, works flawlessly!
