### ISSUE TITLE
Home Assistant log warnings related to device_state_attributes and discovery_info.get('name')

### ISSUE THREAD

**Issue by sierraalpha83** [jheling/freeathome#121]
Hi,

I observed two warnings from home assistant. The component itself is working fine.

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 18:00:18 (24 occurrences)
Last logged: 18:00:18

Entity cover.rolladen_kind_2_w_kind_2 (<class 'custom_components.freeathome.cover.FreeAtHomeCover'>) implements device_state_attributes. Please report it to the custom component author.
Entity cover.rolladen_wc_gastetoilette (<class 'custom_components.freeathome.cover.FreeAtHomeCover'>) implements device_state_attributes. Please report it to the custom component author.
Entity cover.rolladen_arbeitszimmer_arbeitszimmer (<class 'custom_components.freeathome.cover.FreeAtHomeCover'>) implements device_state_attributes. Please report it to the custom component author.
Entity cover.rolladen_kuche_w_kuche (<class 'custom_components.freeathome.cover.FreeAtHomeCover'>) implements device_state_attributes. Please report it to the custom component author.
Entity cover.rolladen_kuche_n_kuche (<class 'custom_components.freeathome.cover.FreeAtHomeCover'>) implements device_state_attributes. Please report it to the custom component author.

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 18:00:22 (1 occurrences)
Last logged: 18:00:22

Detected integration that accessed discovery_info.get('name') instead of discovery_info.name; this will fail in version 2022.6. Please report issue to the custom component author for freeathome using this method at custom_components/freeathome/config_flow.py, line 50: if not zeroconf_info.get("name", "").startswith("free@home"):

**Comment by Tho85** [comment]
Thanks for the report, this is fixed in PR #115. However, the PR is still a draft, since it contains changes that only work with HA >= 2022.1, which has not been released yet.

So you can just ignore these messages for now and upgrade the component as soon as HA 2022.1 is out.
