### ISSUE TITLE
Deprecation warning discovery_info['host']

### ISSUE THREAD

**Issue by derjoerg** [jheling/freeathome#126]
Hi,

I see the following warning in HA-Logs

`Detected integration that accessed discovery_info['host'] instead of discovery_info.host; this will fail in version 2022.6. Please report issue to the custom component author for freeathome using this method at custom_components/freeathome/config_flow.py, line 55: await self.async_set_unique_id(zeroconf_info["host"])`

2022.6 will arrive "soon".

**Comment by DarkTempIar** [comment]
Same here, still no reaction from code owner :(

**Comment by EnricoBilla** [comment]
I opened #128, the problem is fixed. Can you confirm it's working?
