### ISSUE TITLE
"Error setting up: Import Error" failure after HA update at 22 August 2022

### ISSUE THREAD

**Issue by zillawilli** [jheling/freeathome#138]
Hello.
First of all, I have to say thank you for the great HA extension.
I thought there was nothing in HA for the freeathome system.

I did a complete update in HA yesterday, 22 August 2022. Now it is unfortunately that the freeathome extension now no longer works.
It appears the error message "Error setting up: Import Error".
Can you please help?

What have I done so far:
The configuration.yaml was checked. Should fit according to the readme.
Raspberry was completely rebooted several times.

nice greetings from Tyrol / Austria
willi

**Comment by eddieddieddi** [comment]
Hi,

text me if you are german. My english is very bad, but i have help for you

Von: zillawilli ***@***.***>
Gesendet: Montag, 22. August 2022 12:40
An: jheling/freeathome ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [jheling/freeathome] "Error setting up: Import Error" failure after HA update at 22 August 2022 (Issue #138)


Hello.
First of all, I have to say thank you for the great HA extension.
I thought there was nothing in HA for the freeathome system.

I did a complete update in HA yesterday, 22 August 2022. Now it is unfortunately that the freeathome extension now no longer works.
It appears the error message "Error setting up: Import Error".
Can you please help?

What have I done so far:
The configuration.yaml was checked. Should fit according to the readme.
Raspberry was completely rebooted several times.

nice greetings from Tyrol / Austria
willi

-

**Comment by zillawilli** [comment]
Hallo.
Zunächst einmal muss ich mich für die tolle HA-Erweiterung bedanken.
Ich dachte, es gäbe in HA nichts für das Freeathome-System.

Ich habe gestern, 22. August 2022, ein komplettes Update in HA gemacht. Nun ist es leider so, dass die freeathome-Erweiterung nun nicht mehr funktioniert.
Es erscheint die Fehlermeldung "Fehler beim Einrichten: Importfehler".
Können Sie mir bitte helfen?
![Home Assistant](https://user-images.githubusercontent.com/74373923/185915975-c65631ea-39ec-4b1c-846d-16bc3bcb5661.png)


Was habe ich bis jetzt gemacht:
Die configuration.yaml wurde überprüft. Sollte laut Readme passen.
Raspberry wurde mehrmals komplett neu gebootet.
Auch der AP von freeathome wurde neu gestartet.
User und Passwort wurden auch überprüft.

Schöne Grüße aus Tirol / Österreich
willi

**Comment by eddieddieddi** [comment]
Moin moin,

Bei mir hilft es Wenn du im Terminal (siehe Foto) das hier eingibst.
Siehe markierte Zeilen.
Die Prozedur musst du leider nach jedem HA Update machen. Habe auch noch keine dauerhafte Lösung. Melde dich mal ob das geklappt hat.

Viele Grüße aus Hannover.


[image0.jpeg]


[image1.jpeg]
Von meinem iPhone gesendet

Am 22.08.2022 um 13:59 schrieb zillawilli ***@***.***>:

﻿

Hallo.
Zunächst einmal muss ich mich für die tolle HA-Erweiterung bedanken.
Ich dachte, es gäbe in HA nichts für das Freeathome-System.

Ich habe gestern, 22. August 2022, ein komplettes Update in HA gemacht. Nun ist es leider so, dass die freeathome-Erweiterung nun nicht mehr funktioniert.
Es erscheint die Fehlermeldung "Fehler beim Einrichten: Importfehler".
Können Sie mir bitte helfen?
[Home Assistant]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F74373923%2F185915975-c65631ea-39ec-4b1c-846d-16bc3bcb5661.png&data=05%7C01%7C%7Cb4980c2fa1d94b6a242a08da8435b4b8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637967663440430385%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HAspqUnnbaqUQF7W40GGmJoinECw4%2Fu%2F%2BnXQ31WYoAU%3D&reserved=0>

Was habe ich bis jetzt gemacht:
Die configuration.yaml wurde überprüft. Sollte laut Readme passen.
Raspberry wurde mehrmals komplett neu gebootet.
Auch der AP von freeathome wurde neu gestartet.
User und Passwort wurden auch überprüft.

Schöne Grüße aus Tirol / Österreich
willi

**Comment by zillawilli** [comment]
Hallo Eddi

Kann leider kein Bild sehen oder öffnen.
Kannst Du es bitte nochmal versuchen.

Danke
willi

**Comment by eddieddieddi** [comment]
***@***.***

Das eingeben:
docker exec -it homeassistant /bin/bash

DANACH

apk add libsodium

DANACH neustarten


Von: zillawilli ***@***.***>
Gesendet: Montag, 22. August 2022 14:14
An: jheling/freeathome ***@***.***>
Cc: eddieddieddi ***@***.***>; Comment ***@***.***>
Betreff: Re: [jheling/freeathome] "Error setting up: Import Error" failure after HA update at 22 August 2022 (Issue #138)


Hallo Eddi

Kann leider kein Bild sehen oder öffnen.
Kannst Du es bitte nochmal versuchen.

Danke
willi

-

**Comment by Tho85** [comment]
@zillawilli (@eddieddieddi) Der Fehler wurde vor ca. einer Woche in #134 behoben. Wenn ihr die free@home-Komponente updated, ist dieser Workaround nicht mehr nötig.

The issue has been fixed in #134, updating the component should be enough to get things up and running again.

**Comment by zillawilli** [comment]
Hallo Tho85

Is it possible to update with one click?

regards
willi

**Comment by Tho85** [comment]
I'm not sure, it depends on your installation. If you use HACS, it may be possible there, but I can't tell for sure.
