### ISSUE TITLE
input_boolean not working correctly

### ISSUE THREAD

**Issue by derjoerg** [jheling/freeathome#144]
Hi,

first of all: I LOVE this integration!

Now to my problem :)

I created an boolean input-helper in HA called: input_boolean.sleep
For that helper I created an automation, which - based on on or off - do several things (like closing a shutter and turn on a light).
Afterwards I exposed this helper through emulated_hue to F@H. It is shown correctly in F@H as light.
I then put this "light" on my 7'- panel.

So now the following happens:
- If I toggle the helper in HA it is not reflected in F@H
- If I turn on the "light" in F@H it is correctly updated in HA to "on" and my automation kicks in, BUT
- - After some seconds (around 3) it automatically went to "off" in F@H, without modifying the state in HA so I can't turn it off through F@H (as it already is off) [in HA it is still "on" and I can turn it to "off"
- - If I click on the "light" within the first three seconds (see above) it is correctly updated in HA to "off" and my automation kicks in

What am I doing wrong?

BTW: I have several other boolean input-helper configured to e.g. capture a F@H movement-sensor or the doorbell and they work as expected.

Thanks a lot in advance
Joerg

**Comment by derjoerg** [comment]
Ah,

thanks for the hint.

I'm already on 2022.11.3 and using new features. So a downgrade is not possible for me.

But I will monitor these links.

**Comment by SimonKbg** [comment]
Same here!

**Comment by derjoerg** [comment]
Hi,

I finally got it to work :)

I don't use emulated Hue anymore, but the local Rest-Api with Node-Red.

It's a kind of hack, but as it uses the official APIs I think it might be a bit future-proof.
