### ISSUE TITLE
Configurazione non riuscita

### ISSUE THREAD

**Issue by alfonsomainardi** [jheling/freeathome#149]
MI escono questi errori:

[546782238784] Error handling message: Unable to find service freeathome.dump (unknown_error) from 2.118.160.158 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)
15:08:43 – (ERRORE) Home Assistant WebSocket API
websocket_api script: Error executing script. Service not found for call_service at pos 1: Unable to find service freeathome.dump
15:08:43 – (ERRORE) helpers/script.py
Error setting up entry 192.168.1.102 for freeathome
15:03:59 – (ERRORE) Busch Jaeger/ABB Free@Home (integrazione personalizzata) - il messaggio si è verificato per la prima volta alle 14:51:48 e compare 3 volte
Connection with SysAP lost
15:03:47 – (AVVISO) Busch Jaeger/ABB Free@Home (integrazione personalizzata)
Unexpected exception
15:03:47 – (ERRORE) Busch Jaeger/ABB Free@Home (integrazione personalizzata)

**Comment by alfonsomainardi1989** [comment]
Logger: homeassistant.config_entries
Source: custom_components/freeathome/fah/pfreeathome.py:712
Integration: Busch Jaeger/ABB Free@Home ([documentation](https://github.com/jheling/freeathome))
First occurred: 19:07:07 (1 occurrences)
Last logged: 19:07:07

Error setting up entry 192.168.1.102 for freeathome
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/freeathome/__init__.py", line 77, in async_setup_entry
    await sysap.find_devices()
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 897, in find_devices
    await self.xmpp.find_devices(self._use_room_names)
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 712, in find_devices
    filter_mask = int(option.get('mask'), 16) # e.g. '00000001' -> 0x00000001
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by alfonsomainardi1989** [comment]
helpme!

**Comment by alfonsomainardi1989** [comment]
I tried it doesn't come out in the services help me understand thank you very much

**Comment by alfonsomainardi1989** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:150
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 16:55:27 (8 occurrences)
Last logged: 18:11:44

[546953511120] Error handling message: Unable to find service freeathome.dump (unknown_error) from 2.118.160.158 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)
[546951725744] Error handling message: Unable to find service freeathome.dump (unknown_error) from 2.118.160.174 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)

**Comment by jheling** [comment]
ok, the error starts in the source fah/pfreeathome.py at line 712. Can you add a new line in this source so that the code around line 712 looks like this:

                        option = channel_selector_parameter.find("./valueEnum/option[@key='{}']".format(parameter_value))
                        # Get filter mask from mask attribute
                        if option is not None: 
                            filter_mask = int(option.get('mask'), 16) # e.g. '00000001' -> 0x00000001

**Comment by alfonsomainardi1989** [comment]
thanks, can someone help me because I'm not so practical thanks to whoever will help me

**Comment by alfonsomainardi1989** [comment]
mi restituisce questo errore

Errore
Impossibile caricare il flusso di configurazione: {"message":"Invalid handler specified"}

**Comment by alfonsomainardi1989** [comment]
I tried like you said it doesn't work! if you can help me, greetings.

**Comment by jheling** [comment]
Hello, i have edited your pull request. Can you try this new version?

**Comment by alfonsomainardi1989** [comment]
ok

**Comment by jheling** [comment]
Can you show the traceback of this error?

**Comment by alfonsomainardi1989** [comment]
tt ok funziona! grazie mille

**Comment by jheling** [comment]
ok,  good luck with your installation
