### ISSUE TITLE
Steps for install free@home

### ISSUE THREAD

**Issue by mariskabean** [jheling/freeathome#152]
I'm so happy  you found something to use free@home with the Home Assistant. Home Assistant is still very new to me. At the moment I have Home Assistant running on a virtual machine. I plan to purchase an Odroid M1 starter kit but that is for later. 
I have HACS installed on Home Assistant and now I would like to get free@home working. I am adding a custom repository but what is the URL to the repository I should use? Is this the last thing I need to do or do I need to do more actions? Sorry I need a little bit help. 
Thank you :)

**Comment by mariskabean** [comment]
In the meantime, one step further :) I select Settings - Devices & Services - Add integration and there I see Busch Jaeger/ABB Free@Home, cool. But when I click on it I get the following message: 
Config flow could not be loaded: {"message": "Invalid handler specified"} 
How can I solve this?

**Comment by jheling** [comment]
Hello,  Mariskabean, 
There seems to be something wrong with the integration screen. It will probably take some to find the error.
In the mean time you can try to  get it working through the configuration.yaml.

**Comment by siyman** [comment]
Hi there,

was running into the same issue. After manually editing configuration.yaml I receive an error in my log files which looks like that:
`Logger: homeassistant.config_entries
Source: config_entries.py:2077
First occurred: 12:43:08 (3 occurrences)
Last logged: 12:43:12

Error occurred loading flow for integration freeathome: No module named 'custom_components.freeathome.config_flow'`

Any help appreciated.
