### ISSUE TITLE
Tutorial for installation

### ISSUE THREAD

**Issue by Alox-K** [jheling/freeathome#157]
Thank you for this great plugin. Since I was completely flashed how great Home Assistant and free@home are working toghether now, I made a Tutorial about how to install HA and implement f@h.
I'd like to contribute it for this project, maybe jheling would like to add a link or something to this github project to close this issue.
I hope you like it and thanks again for this work.

https://youtu.be/9xfUhRiwK_s

**Comment by jheling** [comment]
Thank you very much.  I have added the link to the documentation
