### ISSUE TITLE
Connecting / setup free@home

### ISSUE THREAD

**Issue by jovana** [jheling/freeathome#161]
Hi,

I want to set up this custom_component but I have some issues connecting.
I have enabled the API user in the sysAp. 
<img width="604" alt="Scherm­afbeelding 2023-05-25 om 12 32 38" src="https://github.com/jheling/freeathome/assets/645456/f865e1ac-46af-4f5e-87e3-1bc2ce93cc45">

After that, I added the info in configuration.yaml, and after a restart, it detect the sysAp box.
<img width="304" alt="Scherm­afbeelding 2023-05-25 om 14 23 55" src="https://github.com/jheling/freeathome/assets/645456/41eae366-3668-41f0-b2e7-c5d99df84fb0">

Click on the configure button and enter the details again.
<img width="443" alt="Scherm­afbeelding 2023-05-25 om 14 24 47" src="https://github.com/jheling/freeathome/assets/645456/a1215892-310e-4e7a-9c8d-05ebbdfccbc8">

It gives me the error "check the username". Checking the log I see only this:

```
023-05-25 10:26:06.273 ERROR (MainThread) [custom_components.freeathome.fah.settings] user not found
2023-05-25 10:26:18.844 ERROR (MainThread) [custom_components.freeathome.fah.settings] user not found
2023-05-25 10:28:02.149 ERROR (MainThread) [custom_components.freeathome.fah.settings] user not found
2023-05-25 10:28:10.681 ERROR (MainThread) [custom_components.freeathome.fah.settings] user not found
2023-05-25 10:32:26.622 ERROR (MainThread) [custom_components.freeathome.fah.settings] user not found
2023-05-25 10:33:17.741 ERROR (MainThread) [custom_components.freeathome.fah.settings] user not found
2023-05-25 12:24:52.419 ERROR (MainThread) [custom_components.freeathome.fah.settings] user not found
```

What can I do to fix this issue?

thx for helping!
Jo

**Comment by victorclaessen** [comment]
Can you try the username you normally log into the SysAp with? (So not the one you see in the REST api)

**Comment by victorclaessen** [comment]
🤔
* Can you check in the app which user you are logged in with? In the top right corner there should be an icon of a person with a dropdown menu, which should say "Logged in as: xxxx"
* Otherwise, can you check in the app under "User administration" which users there are?

**Comment by jovana** [comment]
> 🤔
> 
> * Can you check in the app which user you are logged in with? In the top right corner there should be an icon of a person with a dropdown menu, which should say "Logged in as: xxxx"
> * Otherwise, can you check in the app under "User administration" which users there are?

YES!! This did the trick! The username is "Bewoner" (it's dutch for resident). Okay let's see what we can do now.

Thanks for helping!
