### ISSUE TITLE
Please export / expose also virtual devices with serial number 6000xxxxxxx

### ISSUE THREAD

**Issue by janpschaefer** [jheling/freeathome#162]
It would be really great to also export virtual free@home devices with serial 6000 to HA

**Comment by jheling** [comment]
Hello, i have finally found some time to dive into this. Can give me an example of such a virtual device?
I have looked at the requirements for these virtual devices:  A system access point 2.0 with at least version 2.6.0 must be available.
Unfortunately i have a system access point 1.0.

**Comment by jheling** [comment]
hello, what i need is a dump of the free@home configuration as described in the home page.  That will give me some more information about the structure of the virtual free@home devices .

**Comment by zernima** [comment]
> hello, what i need is a dump of the free@home configuration as described in the home page. That will give me some more information about the structure of the virtual free@home devices .

Do you still need a Dump?
A Integration of Virtual devices where great und very helpful.

**Comment by KKlausl** [comment]
[freeathome_dump_192.168.0.18_2023_08_27_21_02_09.txt](https://github.com/jheling/freeathome/files/12448646/freeathome_dump_192.168.0.18_2023_08_27_21_02_09.txt)

Hopefully this Dump as a Text-File helps. If you need the file in some other format - please tell me, how. I was not able to use ubuntu correctly...

**Comment by Tho85** [comment]
Could you try my code at #164, i.e. the code from [this branch](https://github.com/Tho85/freeathome/tree/Tho85/only-ignore-hue-devices)? I added a small change there that may fix this issue.

**Comment by KKlausl** [comment]
that´s it - you´re a hero!! thanks, it works perfectly!! I will integrate all new entities and use resp test them... :)))

**Comment by Tho85** [comment]
Nice! Looking forward to more feedback from other people here.

**Comment by zernima** [comment]
Thanks very much. I've also tested it and works great.

**Comment by Tho85** [comment]
Fixed via #164
