### ISSUE TITLE
Integration not possible - Requirements for freeathome not found: ['slixmpp==1.8.3'].

### ISSUE THREAD

**Issue by m4rsi** [jheling/freeathome#165]
Hi, 
integration does not seem to work for me as I keep getting error messages. 

I have added the "freeathome" folder to my HomeAssistant config folder "\\192.168.188.167\config\custom_components\freeathome". After restarting HomeAssistant the Busch/Jäger Free@Home integration is not automatically detected and when I select it from "Add new integration" I get an error 500 after some time. 

I tried to configure "configuration.yaml" by myself, but the error is still there.

home-assistant.log says:
homeassistant.requirements.RequirementsNotFound: Requirements for freeathome not found: ['slixmpp==1.8.3'].

**Comment by jheling** [comment]
hello, could you try to change the slixmpp version in  requirements.txt and manifest.json to 1.8.4?

**Comment by m4rsi** [comment]
That did the trick. Thanks alot [jheling](https://github.com/jheling)
