### ISSUE TITLE
Smoke Detector

### ISSUE THREAD

**Issue by David-Butzek** [jheling/freeathome#173]
Hello, is it possible to integrate the smoke detectors?

**Comment by jheling** [comment]
Hello, that should be possible. Can you make a dump of your free@home configuration as described in section 1 of debugging?

**Comment by David-Butzek** [comment]
[home-assistant_2023-12-18T20-33-39.691Z.log](https://github.com/jheling/freeathome/files/13826385/home-assistant_2023-12-18T20-33-39.691Z.log)
[Projektdokumentation-2.pdf](https://github.com/jheling/freeathome/files/13826386/Projektdokumentation-2.pdf)

**Comment by David-Butzek** [comment]
Good morning, I hope this is the correct data

**Comment by jheling** [comment]
Hello, i was expecting something else.  In the readme for this integration is also a debug section.  Here is described how to make a dump of the free@ home configuration. This can be done in home assistant. The result is an xml file that is more detailed than the pdf you sent.

**Comment by David-Butzek** [comment]
[freeathome_dump_192.168.178.20_2024_01_04_22_41_31.zip](https://github.com/jheling/freeathome/files/13835819/freeathome_dump_192.168.178.20_2024_01_04_22_41_31.zip)

sorry, misunderstood. But now it should be fine

**Comment by jheling** [comment]
yes, this is ok, now i have to find some time

**Comment by jheling** [comment]
Could you try if #178 works for you?

**Comment by David-Butzek** [comment]
Good morning, unfortunately #178 doesn't work

**Comment by jheling** [comment]
ok, do you see any new binary smoke detectors / co detectors in your home assistant?

**Comment by David-Butzek** [comment]
No

**Comment by jheling** [comment]
Are there any errors in the home assistant log?

**Comment by David-Butzek** [comment]
where can I find the log file?

**Comment by David-Butzek** [comment]
[Uploading home-assistant_2024-02-02T04-49-19.540Z.log…]()
Must be that, right?

**Comment by jheling** [comment]
I have some trouble with opening the log

**Comment by David-Butzek** [comment]
[Uploading home-assistant_2024-02-02T20-25-22.658Z 2(1).log…]()

**Comment by David-Butzek** [comment]
better? The time I made the changes, the interface didn't work

**Comment by jheling** [comment]
no, when i click the log, the page reloads.  A save link as does also not work.  It looks like you 'Commented' the message before the upload was complete, all the last logs show the text uploading. Maybe zipping the log works better?

**Comment by David-Butzek** [comment]
[home-assistant_2023-12-18T20-33-39.691Z.log](https://github.com/jheling/freeathome/files/14150533/home-assistant_2023-12-18T20-33-39.691Z.log)

**Comment by David-Butzek** [comment]
Alright now

**Comment by jheling** [comment]
If i look at the log the whole freeathome integration doesn't seem to work.  It looks similar to issue #172 . I think you should reinstall the integration.  After that the lines with 'slixmpp.exceptions.IqTimeout' should not appear.

**Comment by David-Butzek** [comment]
free@home is working again. why does home assistant show 2x free@home?

**Comment by jheling** [comment]
This has probably to do with ip4 and ip6. See #176 for more information. Now you have free@home working again, do you see new binary sensors or an error regarding binary sensors in the logging?

**Comment by David-Butzek** [comment]
free@home works without any problems. There are no new sensors or devices. I also tried #178 again but only 13 devices and 26 devices are shown

**Comment by jheling** [comment]
If there are less devices found with #178, there should be at least one error in the log.

**Comment by David-Butzek** [comment]
[home-assistant_2024-02-08T04-36-45.271Z.log](https://github.com/jheling/freeathome/files/14204317/home-assistant_2024-02-08T04-36-45.271Z.log)

**Comment by David-Butzek** [comment]
I have made. Unfortunately Freeathome doesn't work

**Comment by David-Butzek** [comment]
[home-assistant_2024-02-08T04-39-46.848Z.log](https://github.com/jheling/freeathome/files/14204329/home-assistant_2024-02-08T04-39-46.848Z.log)

**Comment by jheling** [comment]
Thank you for the logs unfortunately, they did not help me for finding out what goes wrong.

When I look at the freeathome dump you made there are 4 smoke sensors and 3 CO sensors in your system. They have the following serial ids:
Smoke detectors serial: E11260372669, E11260372668, E11260372678, E11260372649
CO detector serial: E11253502774, E11253502887, E11253502753

Could you adjust the logging level in your configuration.yaml like this? :

logger:
  default: warning
  logs:
    custom_components.freeathome: info

After changing the configuration.yaml you should restart home assistant.
This should show extra information in the logfile like:
add device FahBinarySensor ABB700C8605D/ch0003 Sensoreinheit 2-fach R (Hal), datapoints {1: 'odp0000', 2: 'odp0004', 3: 'odp0005', 16: 'odp0001', 32: 'odp0002', 33: 'odp0003', 40: 'odp0007'}, parameters {}
I expect that those sensor serial ids will show up in the logging and give me some extra information.

**Comment by David-Butzek** [comment]
If I enter that into my yaml I can't have it checked before restarting

logger:
default: warning
logs:
custom_components.freeathome: info

**Comment by David-Butzek** [comment]
and should I do #178 before changing the yaml

**Comment by jheling** [comment]
Oh sorry, the yaml should be indented with 2 spaces for each level , like this: 
logger: 
  default: warning
  logs:
    custom_components.freeathome: info

It does not matter when you change the yaml. You can do it before or after you apply the sources of #178 to your installation. The new logging will be active when you restart HA.

**Comment by David-Butzek** [comment]
Good morning and sorry for the late reply. I get this error message as soon as I check the configuration

Konfigurationswarnungen
Invalid config for 'logger' at configuration.yaml, line 65: expected a dictionary for dictionary value 'logger->logs', got None
Invalid config for 'logger' at configuration.yaml, line 66: 'custom_components.freeathome' is an invalid option for 'logger', check: logger->custom_components.freeathome

**Comment by jheling** [comment]
These comments do not show the identations. It should look like this:

```
logger:
  default: warning
  logs:
    custom_components.freeathome: info
```

**Comment by David-Butzek** [comment]
Good morning,
it worked.
What data do you need?

**Comment by jheling** [comment]
Good Morning. Can you find the lines that belong to the smoke detector with the id E11260372669? Or one of the other id's I mentioned above

**Comment by David-Butzek** [comment]
![IMG_5994](https://github.com/jheling/freeathome/assets/139677917/bf3e721f-ad30-4210-95b0-05b4006fa451)

**Comment by jheling** [comment]
No, i mean the home assistant logging. If i set the language to german: einstellungen, system, protocolle, Vollständige Protokolle laden.  In English that is logs

**Comment by David-Butzek** [comment]
[home-assistant_2024-02-17T10-20-00.286Z.log](https://github.com/jheling/freeathome/files/14318479/home-assistant_2024-02-17T10-20-00.286Z.log)

**Comment by David-Butzek** [comment]
I find it in the log file

**Comment by jheling** [comment]
Ok, now i see the problem:

2024-02-17 10:59:25.788 INFO (MainThread) [custom_components.freeathome.fah.pfreeathome] Device: device id 0121, name id 04B7, serialnumber E11253502753, display name 
2024-02-17 10:59:25.788 INFO (MainThread) [custom_components.freeathome.fah.pfreeathome] Ignoring serialnumber E11253502753, channel_id ch0000, function ID 126 since it is not assigned to a room

All the sensors should be assigned to a room in free@home.  Otherwise they will not be visible in Home Assistant

**Comment by David-Butzek** [comment]
How do I do that? Or What do you mean?

**Comment by jheling** [comment]
You need the original free@home app from busch-jeager, abb. There you need to go Device-configuration/Gerätekonfiguration . For each sensor you can assign a floor and room to the device.

**Comment by David-Butzek** [comment]
Works. Thank you very much.

**Comment by jheling** [comment]
Ok, did you try out the smoke sensor? Is there a test button which also triggers the alarm?

**Comment by David-Butzek** [comment]
Hello,
I triggered a fire alarm today. Unfortunately, I discovered that the status does not change. And is it possible to display the temperature of the smoke detectors?

**Comment by jheling** [comment]
This integration intercepts the messages that are sent when you, for example , push a button to turn on the light. So this integration knows that specific switch is pushed. If a free@home switch was not paired to any light, there would be no message when the button was pushed.  Maybe it is the same with the smoke alarm. Is it all ready paired to 1 other free@home device? If that is all ready the case you could try to see if there are messages sent on the free@home bus. In the debug section of the readme there is also a part 2. Monitoring free@home status updates.  You can use this to see if there are messages sent when there is a smoke alarm.
