### ISSUE TITLE
Question: Access wind alert from Busch Jäger

### ISSUE THREAD

**Issue by Ruko2010** [jheling/freeathome#174]
Hi, 
I have a wether station from Busch Jäger and it triggers a wind allert, if the wind is high over a certain amount of time. I see the weather station in HA, but not the wind alert. When wind alert is triggered, my blinds go up to protect them from damage and they will be locked for about 10 Minutes. But after the wind alert is off, they don't go down again. Only thing i can trigger from busch jäger would be a Scene after the alert, but then I can only close the blinds again. But if the blind are open before the wind alert, I do not want to close them.
My plan is to make an automation that is triggert on the wind alert, save the state of all blinds, open them and put them back to the original state after 10 Minutes after the wind alert is off again.
Do I have to write myself a wind alert in HA, or is it possible to access the windalert generated by busch jäger?

**Comment by jheling** [comment]
Hello, i do not own a weather station. But while looking at the code i saw the PID_WIND_ALARM. Can you show me which binary sensors appear at the weather station?

**Comment by Ruko2010** [comment]
In the Integration, I have the following sensors:
<img width="598" alt="image" src="https://github.com/jheling/freeathome/assets/2239440/108db313-dcac-45da-8fc5-4cce71590e55">
I have no binary sensor regarding the weather station. Problem with the wind strength is, that it is only updated every minute or 30 seconds. So a wind alarm like in the bush jäger app (alarm if the wind is 5 second over XY) is not possible.

**Comment by jheling** [comment]
Ok, you could try another option as described in question  #171. Here  an input_boolean helper in Home Assistant which was exposed to free@home using the emulated Hue Bridge. In free@home this helper was recognized as a switch. This switch should then be connected to the wind-alarm.

**Comment by Ruko2010** [comment]
I understand what the process is, and I will try it. I‘ll report if it works, or fails 😃

**Comment by Ruko2010** [comment]
Ok, i'll tried it but was not successful. 
1. i created a binary_sensor, that was the easy part.
2. I managed to install the [emulated_hue_bridge](https://www.home-assistant.io/integrations/emulated_hue) and by calling the URL http://192.168.10.245:8300/api/v2/lights I see the JSON with my exposed binary sensors.
3. But, my free@home is not seeing the Hue Bridge. When I try to add the Hue integration in free@home, the bridge can't be found:
![image](https://github.com/jheling/freeathome/assets/2239440/245d32a6-c242-4e58-91bc-1db1fe6d2964)

@SimonKbg can you tell me how to include the virtual hue bridge in free@home like you did in #171 ?

**Comment by jheling** [comment]
This is my setup for the emulated Hue bridge in the configuration.yaml:
```
emulated_hue:
  listen_port: 80
  expose_by_default: false
  entities: 
    switch.chain_actuator_230vat_2:
      name: skylight
```
In windows i see this appearing under network as 'Home Assistant Bridge'.
The webinterface of free@home also detects this Home Assistant Bridge.

**Comment by Ruko2010** [comment]
I had a similar config. Do I also need a Physical Hue Bridge to make this work?
I installed the hue App on my iPhone and also there, I do not see the bridge.

**Comment by jheling** [comment]
It should work without it as i don't have any Hue. Did you try the troubleshooting points of the Home Assistant Emulated Hue page?

**Comment by Ruko2010** [comment]
Sorry for the late response. I've been busy.

I've gone through the troubleshooting, and it seams like, Emulated Hue is running:
<img width="599" alt="grafik" src="https://github.com/jheling/freeathome/assets/2239440/c36a2fe8-0c7c-4131-8f8d-b66395f7da09">
<img width="398" alt="grafik" src="https://github.com/jheling/freeathome/assets/2239440/8b0677e3-c340-41aa-9448-422e83b3ca68">

But neighter the Busch Jäger App, nor the Hue App discover my Emulated Bridge as Hue Bridge. Am I missing a step here? Do I have to do something else?

**Comment by jheling** [comment]
Can you compare your setup with this one: https://github.com/jheling/freeathome/issues/171.

**Comment by Ruko2010** [comment]
Ok, I'm one giant step closer now. I updated my SysAP to the newest firmware (automatic download was not enabled) and after the update the Hue Bridge was discovered instantly.
I could now include my binary sensor "windalarm" in Free@home.
But, it was only included as a hue light. I could not change the type of the "windalarm". And I cannot connect my wind alarm to a light, only to blinds. 
For testing purpose, I connected my motion detector to the windalarm-light and the status is transfered to HA instantly, so this is working.
Any ideas on that @jheling ? Maybe there is a way to activate the windalarm in the API natively?

**Comment by jheling** [comment]
yes, lets try to do it with the integration. Can you try to make a dump like described in point 1 of the debugging section of the homepage? This shows the function-id's and pairing-id's of your weather station.  Is it also possible for you to try do point 2 of the debugging section while you have an actual wind-alarm? This should tell us more about the structure of the update message.

**Comment by Ruko2010** [comment]
Here is my dump of the point 1. (i have to rename it from *.xml to *.txt to upload it here. 
[freeathome_dump_192.168.10.103_2024_02_05_08_55_45.txt](https://github.com/jheling/freeathome/files/14162126/freeathome_dump_192.168.10.103_2024_02_05_08_55_45.txt)

It is a bit hard to get a monitor of status change, because i can't determine when a wind alert will be triggered. But if it is really important for you, I'll try to "spinn the wind wheel" manually (if i can reach it, it is mounted really high outside 😃)

**Comment by jheling** [comment]
hello, could you try  #179?

**Comment by Ruko2010** [comment]
Sorry, for the dump question. But how it the correct way to test this?

1. Download the code from the PR
2. Copy all files to custom_components/freeathome
3. Whats next? Just restart?

**Comment by jheling** [comment]
point 2 copy the files and put them in the right directory.
Then a restart of Home Assistant should be enough.
You should see some new sensors at the weather station

**Comment by Ruko2010** [comment]
@jheling done that. Seems to work, I see three new Sensors. I would asume these are the three new alarms, but they are all name "special snow flake", so I can't see which one is which 😃.
<img width="340" alt="image" src="https://github.com/jheling/freeathome/assets/2239440/5c313b9d-0dd1-4038-ba91-f80386fdefc9">

**Comment by jheling** [comment]
Yes, that does not work. I have updated the PR, now you should see better names.

**Comment by Ruko2010** [comment]
Still not working. Now I get a startup error:
```Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 07:41:16 (1 occurrences)
Last logged: 07:41:16

Error setting up entry 192.168.10.103 for freeathome
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/freeathome/__init__.py", line 84, in async_setup_entry
    await sysap.find_devices()
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 949, in find_devices
    await self.xmpp.find_devices(self._use_room_names, self._switch_as_x)
  File "/config/custom_components/freeathome/fah/pfreeathome.py", line 824, in find_devices
    channel_name = names[channel_name_id]
                   ~~~~~^^^^^^^^^^^^^^^^^
KeyError: 577
```

**Comment by jheling** [comment]
I have found the error. The channel_name_id was in a wrong format. I have updated the PR.

**Comment by Ruko2010** [comment]
Yes, this is almost perfekt now. The Names are not 100% correct, but I know now, which alarm is connected to which entity. I'll report back after the wind alarm was triggered. But I think this is done now. I'll just rename the Sensors and give them meaningfull icons.
<img width="902" alt="image" src="https://github.com/jheling/freeathome/assets/2239440/0d525adf-e84e-4555-b6fe-c9ca9e633f7f">
After Renaming:
<img width="900" alt="image" src="https://github.com/jheling/freeathome/assets/2239440/b23d33b0-2c97-4fa1-b4ae-d9797cd68cb2">

**Comment by Ruko2010** [comment]
And just a last question @jheling . Do you know why the rain alert is published as sensor, but the others are binary sensors? Rain alert only displays 0 or 1, so for me this is a binary sensor.
<img width="558" alt="image" src="https://github.com/jheling/freeathome/assets/2239440/419045aa-0e32-4035-a9ae-e6eb85188b5d">

![image](https://github.com/jheling/freeathome/assets/2239440/cf0c9dc4-aae1-4add-b3ae-da73d4bbc597)
![image](https://github.com/jheling/freeathome/assets/2239440/8b01454d-ad0e-4b31-887e-1c950563e033)
This is just a little optical issue in my dashboard:
![image](https://github.com/jheling/freeathome/assets/2239440/d01e1dda-dc76-4b18-95b4-64f02ac04adb)
I know I could probably fix this with a template sensor, but I'm just curious is there is a reason for that.

**Comment by Ruko2010** [comment]
I'm not sure what to look for. I Think the Bush Jäger App just uses the alarms internally for automatiions. It does not show them on a homescreen or something else:
<img width="550" alt="image" src="https://github.com/jheling/freeathome/assets/2239440/05081d5a-1af3-4bc8-89e2-01b18aeac9c2">
<img width="565" alt="image" src="https://github.com/jheling/freeathome/assets/2239440/29fa2e5e-f9b1-4242-bae8-7468d0ee05f6">

**Comment by Ruko2010** [comment]
@jheling We had windy weather this night and I can now confirm, your Code is working. Wind-Alart was triggered successfully.
![image](https://github.com/jheling/freeathome/assets/2239440/57c5af59-ed8b-4775-9440-7f1a7554465c)

**Comment by Ruko2010** [comment]
I'm closing this ticket. Hope you merge #179 with the next release. Thanks for your incredible work!
