### ISSUE TITLE
Integration will be discovered over and over again despite successful integration

### ISSUE THREAD

**Issue by stefanbauer** [jheling/freeathome#176]
Hey there,

This is not a real issue but something I'd like to understand. I have a perfect running free@home integration, but regularly, I get new free@home integration suggestions. Sometimes, there are three or four, every single time, with a different IPv6(?) address. I attached a screenshot.

![CleanShot 2024-01-17 at 09 08 45@2x](https://github.com/jheling/freeathome/assets/3192662/fe36ada9-a333-444a-84e3-02c09662d2be)

Does anyone know where it comes from? Can I just ignore it? Should I set it up every single time? Everything is still working as expected, by the way.

Thanks in advance! Great job here guys!

**Comment by SimonKbg** [comment]
I have the same issue. Already reconfigured the integration over the discovered entity, but that didn‘t changed the issue. 
So I just ignored but yes, I it is a little annoying.

**Comment by jheling** [comment]
Hello, when developing this integration i choose to use the ip address as a unique identification for home assistant. Looking back, i should have chosen the mac adress or something else.  You should give the free@home sysap a fixed ip address, then you won't get any new integrations found.

**Comment by stefanbauer** [comment]
Thanks for getting back. I already have a fixed IP, so that is not the issue. Any other ideas? :-)

**Comment by florianutz** [comment]
As you can see from your screenshot, it is always the ipv6 address. HA finds the V4 IP once and you configure the device. But then HA always finds the V6 as a second device again and again. One idea would be that I can configure in the plugin whether I want V6 and/or V4. @stefanbauer A "dirty" workaround wold be to disable V6 in your HA configuration.

**Comment by stefanbauer** [comment]
Thanks Florian! I know that this is the IPv6 address, but what I'm wondering is, that this address changes for every single discovery of the integration and I don't know where this IPv6 address is coming from? I would have expected it's the free@home AP, but it isn't. It has a different one ;) Anyway... I just disabled IPv6 on HA cause I don't need it anyway. That seems to "solve" the problem :)

Let me know if you need any help or further assisting to improve that. Thanks!

**Comment by florianutz** [comment]
I had the same problem. My Fritzbox and desktop work with IPv6, but I couldn't find a way to configure/enable/disable IPv6 in the Free@home System AccesPoint. Because all of my Home Assistand devices are using IPv4 I have also disabled V6 in HA

**Comment by stefanbauer** [comment]
So here is my conclusion until now. I disabled IPv6 entirely in my whole network, but it's still discovering new integrations. As I said, every single time with a different IPv6 address. I've no clue where this address is coming from. Another screenshot with a different address :D

![CleanShot 2024-01-21 at 09 03 57@2x](https://github.com/jheling/freeathome/assets/3192662/cbee8eb0-81b4-4b47-9073-09a7820746cb)

**Comment by jheling** [comment]
It uses the zeroconf integration to discover free@home.  The documentation says the following:
Zeroconf chooses which interfaces to broadcast on based on the [Network](https://www.home-assistant.io/integrations/network/) integration.

IPv6 will automatically be enabled if one of the selected interfaces has an IPv6 address that is enabled via the Network integration.

**Comment by kingsleyadam** [comment]
I've created a PR that should fix this https://github.com/jheling/freeathome/pull/204, note that after this is merged in it'll show up under discovered devices one more time. Once ignored it'll be ignored permanently.

Or you can choose to delete the integration and set it up again. If you do this then Home Assistant will track any IP address changes over ZeroConf and update accordingly, for those that don't have a static IP assigned, or those who need to change it (e.g. https://github.com/jheling/freeathome/issues/185)
