### ISSUE TITLE
Missing ClimateEntityFeature

### ISSUE THREAD

**Issue by thvd** [jheling/freeathome#180]
In the logbook i see this warning: 

`Entity None (<class 'custom_components.freeathome.climate.FreeAtHomeThermostat'>) implements HVACMode(s): heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please report it to the author of the 'freeathome' custom integration`

Versions:
HA: 2024.3.1
Plugin: Current HEAD master

**Comment by jheling** [comment]
Fixed by #181
