### ISSUE TITLE
Change IP address of free@home AP?

### ISSUE THREAD

**Issue by guerda** [jheling/freeathome#185]
I have a new router and that's why my free@home AP got a new IP address. I cannot use the old IP address.

Is there an option to change the IP address in the free at home component?
I have not found any option in the GUI. I would be ok to change files or entries in sqlite dbs.
I understand from #176 that the IP is the unique identifier so I'm wondering if that's possible.

**Comment by jheling** [comment]
Hello, Maybe there is a way. In my home assistant installation there is a hidden directory named .storage.  Here I see 3 files that contain information about the freeathome integration. core.config_entries, core.device_registry and core.entity_registry.  Maybe you only have to change the host in the core.config_entities file

**Comment by guerda** [comment]
Thank you! I hadn't had the chance to reply here. I actually grepped all files and found it in two or three locations in the .storage folder. I replaced the IP and it works.

**Comment by guerda** [comment]
I replaced the IP in the following two files:
* `.storage/core.config_entries`
* `.storage/core.device_registry`
This was sufficient to update the source. Maybe it's helpful for anybody else having that problem :)
