### ISSUE TITLE
Free@home flex device (double sensor) is not recognized in Home Assistant

### ISSUE THREAD

**Issue by alexio70** [jheling/freeathome#186]
Hey, I have read and double check your issue : #132 but my free@home Flex Devices, double sensor, are not recognized - although the new Flex dimming sensor/ actuator is recognized; could you provide me some guidance to what information is suitable . Thanks a lot

**Comment by alexio70** [comment]
I have double checked if the double Flex sensor is bonded to an Actuator, which is the case. After rebooting both free@home and HA there is no difference; both the right rocker and the left rocker are connected to an actuator (dimmable light, connected to a WL dimmer/sensor). Here is the dump of my freeathome... https://github.com/users/alexio70/projects/2

**Comment by jheling** [comment]
Hello, I tried to take a look at your dump, but the link does not show the xml file

**Comment by alexio70** [comment]
Hi jheling,

Can you find attached compressed attachment?
Thanks for having a look at this; it’s a big problem for my setup that I really want to solve

￼

Mvg

Alexio

**Comment by jheling** [comment]
Hello, I don't see the attachtment

**Comment by alexio70** [comment]
any other recommendation how I can get this across?

**Comment by jheling** [comment]
Can you try to zip the xml file and add it as an attachment to the message?

Op zo 9 jun. 2024 22:30 schreef alexio70 ***@***.***>:

**Comment by alexio70** [comment]
Please find attached ZIP file (357KB).
Mvg

Alexio

￼

**Comment by jheling** [comment]
Hello, a zip file through mail does not seem to work. Could you try it on GitHub.com?

**Comment by alexio70** [comment]
> Hello, a zip file through mail does not seem to work. Could you try it on GitHub.com?

If you go to my Github (https://github.com/alexio70/freeathomedump/blob/main/dump) and click the "View raw" you should be able to see the dump file

**Comment by jheling** [comment]
Ok, i am able to see the dump file. Do you a serial number of a double Flex sensor? That saves time for me finding the device.

**Comment by alexio70** [comment]
#ABB702FEFF91 (FVD)
#ABB702FF36C4 (WVQ)
#ABB702FF36CA (TGW)
#ABB702FF36DG (MNO)
#ABB702FF36F8 (MBY)

**Comment by alexio70** [comment]
Hi @jheling have you been able to find something? BR/ Mvg Alexio

**Comment by alexio70** [comment]
Hi, Have you been able to find something?

Met vriendelijke groet,
Alex Bouw
***@***.***

**Comment by jheling** [comment]
I made  #193 . Can you test if this works for you?

**Comment by alexio70** [comment]
> I made #193 . Can you test if this works for you?

@jheling This change made significant improvement!! Thanks. (my devices found in the integration went up from 26 to 31)
There seems to be only 1 still missing; I will analyse it these days and get back to you
