### ISSUE TITLE
Warning message in log file for Thermostats

### ISSUE THREAD

**Issue by Macstar1601** [jheling/freeathome#188]
The following warning message is shown in the log file:

Entity None (<class 'custom_components.freeathome.climate.FreeAtHomeThermostat'>) implements HVACMode(s): heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please report it to the author of the 'freeathome' custom integration

**Comment by oliverlinsenmaier** [comment]
Same on my system. How can we help to solve this?

**Comment by jheling** [comment]
Hello, I have created #214. Could you test this?

**Comment by Macstar1601** [comment]
Hello, Thank you very much for the fix. Unfortunately the error message is still shown in the log

![Uploading IMG_0330.png…]()

**Comment by jheling** [comment]
I cannot see the image.  So you replaced the climate.py with the new one?  In this directory should also be a __pycache__, If you look in this directory,  has the timestamp of the  climate.cphyton changed?

**Comment by Macstar1601** [comment]
I thought it was sufficient to just install the shown update of freeathome in HA. Now I replaced the climate.py manually and the error message disappeared. Thank you very much!!!! Does it now also works correctly when the thermostats are switched to cooling?

**Comment by Macstar1601** [comment]
Unfortunately I receive the following error message when I toogle a thermostat on my dashboard. 

![IMG_0331](https://github.com/user-attachments/assets/c30ee2c7-fe62-4f7f-ac69-ccd722865671)

**Comment by jheling** [comment]
I have changed one line in the climate.py.  The mode should not be HEATING, but HEAT_COOL.

**Comment by Macstar1601** [comment]
Great, many thanks for the quick fix. It works now 👍

**Comment by jheling** [comment]
Nice, The issue you mentioned about cooling is a issue i still have to look at.
