### ISSUE TITLE
Tried to extend the const.py with new function IDs but now the free@home Integrations fails on HA boot

### ISSUE THREAD

**Issue by janpschaefer** [jheling/freeathome#196]
Hi everybody, hi @jheling 

I tried to extend the current const.py file with new function IDs from new devices for the Dimmer class:

![image](https://github.com/user-attachments/assets/23b716d0-3c48-449a-9e77-0c7132fbabeb)

The devices only come with new function IDs but use the same pairing IDs already considered in const.py and light.py

But now I get the following error on HA boot;
![image](https://github.com/user-attachments/assets/a3cb2d05-e21b-4a9b-ad5c-17664c4d32f7)

![image](https://github.com/user-attachments/assets/a7238b67-243b-4607-ad46-ef06944fbb44)

Do I have to consider any other changes on the files? 

BR, Jan

**Comment by jheling** [comment]
Hello Jan.  There are 2 const.py files in this integration.  The one under freeathome should contain a DOMAIN constant. Maybe you pasted the file in the wrong directory? There is also one at freeathome/fah.

**Comment by janpschaefer** [comment]
> Hello Jan. There are 2 const.py files in this integration. The one under freeathome should contain a DOMAIN constant. Maybe you pasted the file in the wrong directory? There is also one at freeathome/fah.

Thank you so much @jheling I really mixed up -.- But know if I have fixed the const.py on main folder level I always get the following error.

![image](https://github.com/user-attachments/assets/c1913f98-4e55-410d-83b7-4b3a09eef028)

I erased the whole free@home folder under custom components and replaced by the one from here official. Same Error....

**Comment by jheling** [comment]
Hello, maybe you can try to delete the integration in home assistant and then adding it again?

**Comment by jheling** [comment]
I saw your pull request and assume the boot error is fixed. Good work!
