### ISSUE TITLE
no devices except lights can be controlled anymore

### ISSUE THREAD

**Issue by guerda** [jheling/freeathome#199]
I had to setup my devices in free at home completely new but since then, I am not able to control or read out any device except lights anymore.
I reinstalled the free at home module, but still, only lights are available. Covers, climate thermostates and plugs cannot be controlled anymore. If I try to do this, there will be just a toast saying something like this:

`Die Aktion cover/close_cover konnte nicht ausgeführt werden. <iq id="ddbd0ae7402440a89a28ecf538ed53a4" type="set" to="mrha@busch-jaeger.de/rpc" from="4ef446e3-7eb2-4d01-ae48-5999828d7e9f@busch-jaeger.de/e1fef97b"><query xmlns="jabber:iq:rpc"><methodCall><methodName>RemoteInterface.setDatapoint</methodName><params><param><value><string>ABB2980E2F51/ch0000/idp0000</string></value></param><param><value><string>1</string></value></param></params></methodCall></query></iq>`

I set up the integration with the defaults (no room names, switch_as_x true)

There's no error in the error logs.  

free at home HACS module version: ac02072
home assistant version: 2024.8.0 in docker (cannot upgrade to 2024.8.1 right now as another integration fails)

**Comment by guerda** [comment]
Ok now it gets strange.  I updated to 2024.8.3 and now I can control covers but lights and wall plugs are not reacting. The same error message occurs.
Is somebody else having issues with the latest versions?
Any idea how to debug this?

**Comment by jheling** [comment]
Hello, while migrating from a raspberry pi 4 to an proxmox setup I noticed that some of the names of the devices had changed.  So I had to adjust some cards to get it working again. If you try to operate the devices through devices and services, do you still have the same behaviour?

**Comment by guerda** [comment]
Hi @jheling !
Thanks for your help 
I reconnected all entities to the dashboard and still most of the stuff does not work. Which surprises me as I used your integration for years already to control fah. That factory reset which happened seemed to break a lot... 

From the **dashboard** I can only control - some lights (binary and dimmed lights), some are not reacting to button press (and are not updated).
Covers don't work at all (and are not updated).
Plugs don't work at all. 
Climate entities don't work at all

From the **device page** I can control _some_ lights (binary and dimmed) but most covers. There are more lights which I can control from here than from the dashboard. 
Plugs don't work at all.
Climate entities don't work at all. 

For both lights and plugs, I'm using the _switch_ entities.
It feels like the integration has old devices still connected which it cannot reach (naturally). 

I removed the integration configuration completely and added it again. I tested now only from the device page, to be sure. Now _other_ entities of fah than before don't work. Dimmers do not work at all anymore, some lights work, plugs still don't work. Covers don't work completely. It's a bit strange and I'm not sure whats going on. I appreciate any pointers, how to fix it.

**Comment by guerda** [comment]
Ok I think it can be closed... I removed the integration configuration, redownloaded the integration again, then used the zero conf flow to configure the fah and now everything works... I really don't know what happened here and why it all broke but for now it seems that it's fixed. 

Sorry to bother you, I assume it was a one time glitch.

**Comment by jheling** [comment]
Ok , i will close this
