### ISSUE TITLE
On Off switches not working correctly

### ISSUE THREAD

**Issue by theuzzy** [jheling/freeathome#20]
Hi,

I'm new to Home Assistant and have installed the freeathome component. When I add a switch to the dashboard I can turn the lights on but I cant turn it off again :(
In the logging it says that I was trying to turn it on again??? 
Looks like the return status is incorrect?
What I'm I missing here?

SysAP firmware: 2.3.1
HA version: 0.98.5

Regards,

**Comment by antasun** [comment]
Hi,

I have the same issue. 

SysAP firmware: 2.3.1
HA version: 0.98.5

**Comment by jheling** [comment]
With the firmware 2.3.0 update there are no more  status messages coming from the Free@home sysap. It is under investigation.

**Comment by theuzzy** [comment]
Hi jheling,

Maybe this will help?
https://github.com/henry-spanka/freeathome-api

Regards,

**Comment by jheling** [comment]
Yes, 

I noticed this a week ago.  The only problem is that it is in javascript. I am in the process of translating to python.  Using the cryptography libraries is a steep learning curve, so it will take some time

**Comment by bartdorlandt** [comment]
I'm having a hard time with getting the free@home documentation. Is there anything that you can share or where I could retrieve it, so I can help you out?

**Comment by jheling** [comment]
There is no official documentation available for connection to the Free@home sysap.  The protocol it uses is XMPP.  I have initially used the sources of this project for figuring out the  messages:  https://github.com/sstadlberger/home.  Now with the developer tools of google chrome is it possible to  monitor the message from/to the sysap while using the official free@home webapp. You can also see the sources the free@home webapp uses at the client size.   My main attention is going to the Crypto.ts of the https://github.com/henry-spanka/freeathome-api project. All these functions have to be rewritten in Python

**Comment by lassem** [comment]
I might be wrong, but switching from `SCRAM-SHA-1` to `SCRAM-SHA-256` should work out of the box in slixmpp.
The library seems to use whatever hashing mechanism that is provided after `SCRAM-`
See https://github.com/poezio/slixmpp/blob/master/slixmpp/util/sasl/mechanisms.py line 197

Unless there is more going on in there; like f.ex. the key derivation stuff that on first sight looks interesting.

**Comment by theuzzy** [comment]
Hello,

Is there a way to schedule (ones a minute or so) a light switch update for the time being?

def update_light(self, device_id, channel):

Regards,

**Comment by lassem** [comment]
Okay, I see what is going on now. There's a new cryptho scheme on all the rpc calls. I guess that requires some work. Poly 1305 support also seems to be required, and that is not part of standard python libs afaict. Another dependency in other words.

**Comment by jheling** [comment]
It was more work than anticipated.  Now the handshake of the new crypto scheme works. The last problem i have are the message which i don't see in slixmpp. With wireshark I see them being send.  I hope i can update the repository later this week.

**Comment by bartdorlandt** [comment]
Hi Johan, thanks for your update. I see it is working a lot better now. 
I did notice that light information isn't correctly pulled from FaH. In other words, they are on, but shown off in homeassistant. 

Are you already aware of this?

**Comment by jheling** [comment]
At the start of home assistant, a complete list of devices is pulled from FAH, with the actual status. After that , FAH pushes status messages. about the devices  These messages used to be plain xml, but with the 2.3.0 firmware these messages are encrypted.  That's why the light information isn't correct after a while.

**Comment by jheling** [comment]
I have just updated the repository. The problems  with the status should now be resolved.

**Comment by bartdorlandt** [comment]
Thanks, that was a big update. Unfortunately I don't see the switches being updated in HA. This weekend I should have a bit more time to try this out and dive into your code.

**Comment by theuzzy** [comment]
Hi jheling,

Thank you for the update, but same as bartdorlandt, unfortunately I don't see the switches being updated in HA.

Regards,

**Comment by jheling** [comment]
Is the orginal fah app working allright? Maybe a reset of the sysap will work

**Comment by bartdorlandt** [comment]
The fah app is working and reacting as expected.


Apologies for the introduced errors by autocorrection on my mobile device.

**Comment by theuzzy** [comment]
> The fah app is working and reacting as expected. Apologies for the introduced errors by autocorrection on my mobile device.

How did you fix it? because a reset of the sysap and a restart of HA didn't work.

Regards,

**Comment by dbrouwer1979** [comment]
I am on version 2.4.0 and have no errors.

**Comment by bartdorlandt** [comment]
> How did you fix it? because a reset of the sysap and a restart of HA didn't work.

To clarify, my reaction was on "is the original fah working as expected":

- The Free@home android app **is** working as expected. 
- the HA + freeathome integration **is not** working as expected.

F@H version 2.3.1

Cheers.

**Comment by Earthwings** [comment]
I just updated freeathome and from a quick look the status is now updated fine again, thanks for fixing :+1: 
I am also on firmware version 2.4.0 like @dbrouwer1979 

Seems the update introduced a dependency on packaging which I didn't have yet. I changed it like this which worked for me:

```
diff --git a/freeathome/__init__.py b/freeathome/__init__.py
index 593ad2d..9c09b55 100644
--- a/freeathome/__init__.py
+++ b/freeathome/__init__.py
@@ -5,7 +5,7 @@ from homeassistant.helpers.discovery import load_platform
 from homeassistant.const import CONF_HOST, CONF_USERNAME, CONF_PASSWORD, CONF_PORT
 import homeassistant.helpers.config_validation as cv
 
-REQUIREMENTS = ['slixmpp==1.4.2', 'libnacl==1.6.1']
+REQUIREMENTS = ['slixmpp==1.4.2', 'libnacl==1.6.1', 'packaging']
 
 
 DOMAIN = 'freeathome'
```

**Comment by theuzzy** [comment]
> > How did you fix it? because a reset of the sysap and a restart of HA didn't work.
> 
> To clarify, my reaction was on "is the original fah working as expected":
> 
> * The Free@home android app **is** working as expected.
> * the HA + freeathome integration **is not** working as expected.
> 
> F@H version 2.3.1
> 
> Cheers.

Ah ok same problem as I have. :( Nothing has changed as of the version from sept. I can switch lights on and off but the status is not showing correctly.

I'm also using F@H version 2.3.1
Is there some debug option?

regards,

**Comment by jheling** [comment]
I have defined two separate  users accounts in the sysap, one for my production rpi  and one for my test rpi.  While testing I noticed that using the same user account on different devices results in stopping of the update messages. A reset works for me.

**Comment by bartdorlandt** [comment]
After the last automatic upgrade of FaH I disabled automatic updates. This time this caused the issue. I have now upgraded to version 2.4.0 and everything seems to be working flawlessly! 

Lights, sensors, all seems to work just fine. Forgot to test the screens though and the little one is already sleeping. Hopefully I don't forget to test tomorrow moring. 

@theuzzy, upgrade to 2.4.0 (wait for all the light switches to update) restart HA and enjoy the show.

PS. anyone tried the double tap feature of 2.4.0 where you can combine a scene as a second option to the default behavior of turning on a light? Just did that and I looks like a great addition!

Thanks Johan for the great work!

**Comment by theuzzy** [comment]
aah great stuff. I've upgraded to 2.4.0 and everything is working!
Thank you for the fix and for this great plugin!

Regards,
