### ISSUE TITLE
No messages without state change

### ISSUE THREAD

**Issue by NeoBlack** [jheling/freeathome#202]
Hi everybody,
I have a problem, and I'm not sure if it's due to free@home or the integration, or maybe it's due to me ;)

I have the following problem:

1. A motion sensor switches a lamp on
2. I press the free@home switch connected to the bus to turn the lamp off again.

Problem: The lamp stays on. I have to press the "on" switch first and then the "off" switch so the message arrives in Home Assistant. For me, it looks like free@home only sends a message when the switch state changes or the integration only sends the message when there is a state change.

If I monitor the entity in HA, I can see that a message only comes when it changes from on to off and vice versa. If I press multiple times, e.g., the "off"-Site of the button, only one message arrives in HA.

Can we solve this?

**Comment by kingsleyadam** [comment]
@NeoBlack , you may want to implement the updates using [events](https://github.com/jheling/freeathome?tab=readme-ov-file#events).

The switch sensor state can be disconnected with the actual state of the light if the light is controlled by some other source.

**Comment by NeoBlack** [comment]
Thank you for the hint. I have modified parts of my automation to use events, which works well. With Node-Red, it is a bit more complex, but it works.

**Comment by NeoBlack** [comment]
@jheling if you think, events are the way to go, we can close this issue. If you think the entities can or should be able to address the issue we can keep it open. I was able to solve my problems with the events.

**Comment by jheling** [comment]
@NeoBlack  yes, in this case you should use events. I see no other solution.
