### ISSUE TITLE
Since updating to HA Core_24.10.02 no connection to F@H possible anymore

### ISSUE THREAD

**Issue by jws75** [jheling/freeathome#205]
I updated to CORE_24.10.02. After Restart Homeassistant displays the message: "Error during setup" (Fehler beim Einrichten)
So I went back to CORE_24.10.01 from the backup and everything worked again.
So I Installed version 02 again and the same error is back.

**Comment by jws75** [comment]
Bei mir kommt dann immer, wenn ich füre die f@h-App oder über die WEB-Oberfläche direkt auf den Smart-AP zugreifen möchte die Meldung, dass es zuviele Anmeldeversuche gab und es läuft eine Wartezeit ab. Es sieht so aus, wie wenn sich Homeassistant immerwieder anmelden möchte und dadurch der Smart-AP die Anmeldung ablehnt.
Wenn ich dann den die f@h-Integration komplett lösche und neu einrichten möchte, dann kommt der Fehler, dass der User oder Passwort nicht passt, obwohl ich mich bisher damit anmelden konnte und mich auch direkt am Smart-AP immernoch anmelden kann.
@derjoerg Du schreibst "die neueste Integration" - Hmm, gab es hier mal ein Update oder ist immernoch 1.0.0 die aktuellste Version?

**Comment by jheling** [comment]
Hello, I have tested the latest version of home assistant on a raspberry 3 with this integration and it works for me.  Did you try it with the latest version of the repository?  The last commit is two weeks old and has to do with discovery through zero conf. In earlier versions this integrations was discovered again and again for some users.

**Comment by jws75** [comment]
I'm using version 1.0.0  of the f@h-Reposetory. Is there a newer version? How can I install this new Version or Commit?
It's working again at the moment, but every time I restart it causes problems.

**Comment by jheling** [comment]
There was an update two weeks ago, but i did't change the version number. Maybe you can check if the changes of #204 are in your local freeathome integration.
