### ISSUE TITLE
support

### ISSUE THREAD

**Issue by bartdorlandt** [jheling/freeathome#22]
Hi Jheling,

I would like to support this project. I also live in the Netherlands and maybe not even far away (Amersfoort).

I installed this on my docker instance of Home assistant and it seems to work great already. As suggested by someone else, it would be superb to have this part of the plugins by default. I was reading up on some of the dependencies, which I would like to help you with. 

I had an issue with my blinds, they wouldn't go up. I'm going to look into that.

Of course I could create some pull requests, but maybe there is a better way. 

Let's start a conversation via: https://twitter.com/BartOmation. If you're not using twitter, let's find another way.

Cheers,
Bart

**Comment by theuzzy** [comment]
Hi guys,

I'm not a programmer but I want to help also, as of sysap free@home version 2.3.0 this script is partly broken and I want to help fixing it.

Regards,

**Comment by miezie** [comment]
I'd also like to support but I am heavily questioning myself if we should not start over since the cloudAPI is there and the XMPP streams in 2.3.x is changed which causes this component to break (and also for example within openhab). 

I already made a bit a deepdive to start understanding the API.

**Comment by jheling** [comment]
Hello Bart, Sorry for the late reaction.  I'm using the sparse time for figuring out the existing javascript code. You can reach me at helingj at google mail. I don't have twitter.

**Comment by miezie** [comment]
Although I understand the reasoning behind the existing javascript code etc. isn't it a better idea to use the API instead? Recently the solutions with the XMPP data stream got out of order with latest updates because the implementation changed. With using the API you will have more stability with code changes... only downside is that it will go via the cloud. But the benefit is that for end users it is a free service. And it is connected anyway... 

Just thinking out loud to make a fruitful and stable joint effort.

**Comment by fotiDim** [comment]
I would be up for keeping the local XMPP API as there are benefits in
having a local API available. Perhaps the official over-the-internet API
could be used as a fallback or could be a separate project.

**Comment by theuzzy** [comment]
+1 for the local XMPP API. I don't want my house to be controlled from outside my home.
So I hope this can be fixed. I'm willing to test some code If I have to.

Is it possible to downgrade the sysap firmware?

Regards,

**Comment by miezie** [comment]
Also check this: https://github.com/henry-spanka/freeathome-api

XMPP API means that you create a component that sniffs XMPP messages and does something with that... all fine, but not that stable.

**Comment by miezie** [comment]
Although I understand all the need for local, I would opt for cloud...
I think with local you only have the programmed stuff in the Free@home webinterface... but with the cloud API you can just use every item in your setup as is and assign functions to it using Home Assistant...

**Comment by miezie** [comment]
After evaluating a lot and improving the code a bit... decided this is the way to go for me :). As a team we can achieve so much more. 

To make it really work within the community we could guide users a bit more on how to get device ids if something is not available. Agree?

**Comment by Tho85** [comment]
Free@home now also has a local REST API, but it doesn't match the functionality of the XMPP API (for now). There is some discussion about this in #80.

Closing this issue, since it has been stale for about two years now.
