### ISSUE TITLE
Basic help

### ISSUE THREAD

**Issue by williamvz** [jheling/freeathome#23]
Sorry guys, I'm not reporting a bug but am really new to Home Assistant and struggling to get this integration to work... 

I have moved all files to the folder. I have updated the configuration file. But I keep on getting the error "Component error: freeathome - Integration 'freeathome' not found."

Any clues? 

![SharedScreenshot](https://user-images.githubusercontent.com/37240069/67809672-71575580-fa99-11e9-9157-616a0e1ff83a.jpg)
![SharedScreenshot2](https://user-images.githubusercontent.com/37240069/67809673-71efec00-fa99-11e9-9861-109c3c528ce9.jpg)

**Comment by dbrouwer1979** [comment]
Hi William, you can email me googles mailservice. dbrouwer1979

**Comment by williamvz** [comment]
Just did that! :)
