### ISSUE TITLE
fire on event for binary_sensor on every press

### ISSUE THREAD

**Issue by kaisten** [jheling/freeathome#26]
Hi,

its not really an issue more an enhancement. I was trying myself but couldn't find a working solution. 
I want to start actions when a light is on and i press the on switch again, for example my bathroom lights are on I press the button again and the speaker starts. Also double click and so on would be possible. 
I was unable to add that for the binary_sensor could some help me out on that?

**Comment by bartdorlandt** [comment]
Is that even seen by HA? 
The double click is new in version 2.4.0 and captured by F@H if a custom scene is linked to the switch. I'm not sure if this is received by HA, since it isn't a state change of the rocker itself. 
Though the custom scene might change states for other entities.

**Comment by miezie** [comment]
You can make HA responding on a light switching on... that's an automation. 

If you want a feature like this you could also start listening on the websocket available in the FAH API.

**Comment by miezie** [comment]
Switches are now more recognized in the component. Does this work for you?

**Comment by kaisten** [comment]
@miezie thank you for the effort. There is event isn't fired again so I cannot tigger anything

**Comment by miezie** [comment]
You should be able to listen on state changes of the light switches and then do your actions.

**Comment by kaisten** [comment]
after a while I tried again but there is no state change trigged anymore after the light is on

**Comment by kaisten** [comment]
I found a way to make use of every press event. Just create a automation in free@home of that actor, this will be recognized as a scene in ha. When that scene will be triggered I can do some actions.
