### ISSUE TITLE
Enhancement request - support for binary input  6241/2.0 and 6241/4.0 

### ISSUE THREAD

**Issue by KucingB** [jheling/freeathome#28]
Hi, 

Are the Busch Jaeger 6241/2.0 U Binaire ingang 2-voudig (Ean 4011395180457) or Busch Jaeger 6241/4.0 U Binaire ingang 4-voudig (Ean 4011395180464) allready supported?

I am using hass with free@home 2.4. It's discovered all my devices, except the 2 listed above.

Did I overlook an option / make a setup mistake, or are these devices not yet supported. 

If this is the case, are there any plans to add these devices? Unfortunately, I am not much of a developer, but as I own both devices,  I can assist with testing if that's of any help.

Thanks for your response. Erik

**Comment by jheling** [comment]
Hello, I have just upgraded the repository.  The get-master-message.py is usable again.  You can run this  in a normal python environment (not homeassistant).  After setting the ipadress, username and password it wil produce a get-master-message.xml which will contain a list of all your devices. The two binary components will have a new device id which i have to add to the freeathome sources.
You can send a mail to helingj  at google mail for help or if you have the get-master-message.xml.
Best, Johan

**Comment by jheling** [comment]
The 2 binary input devices have been added to the repository.
