### ISSUE TITLE
Cover and Switch Actuator Sensor 2/2 with same device ID

### ISSUE THREAD

**Issue by SifuDaigo** [jheling/freeathome#38]
Thanks again for this wonderful integration! Got it finally running on a fresh HA install and it's really really a great addition!
But I ran into another issue:
After grabbing the device IDs with the `get-master-message.py` script it found all my Cover sensor / actuator with the ID `2039 `- but there was one Switch Actuator Sensor 2/2 with the same ID - which naturally now shows up in my HA as a cover after editing the `pfreeathome.py.`

Here's an excerpt from the output:

![image](https://user-images.githubusercontent.com/60067109/77456906-39f89500-6dfc-11ea-9e5d-ff74860800c5.png)

So now the first device shows up in HA twice for both the lamps that are attached - but of course the show up as covers.

Any ideas how to solve this?

**Comment by jheling** [comment]
This very strange. At first It looked like a bug in get-master-message.py. But you are also having this problem in Home Assistant. Could you send me the mastermessage.xml?  Maybe this file can show what is going wrong. My email is helingj at google mail.

**Comment by SifuDaigo** [comment]
Thanks! I just mailed you the file.

**Comment by jheling** [comment]
Hi, I have looked in the mastermessage.xml at the devices with the deviceId 2039. The only explanation i can give it that is indeed the same device type, but each are differently configured. That is a bit strange because busch jeager have sensor/switch actuators and sensor/switch actuators in the programm.  The sensor/schaltaktor has a deviceFlavor of 13.  The other sensor/jalousieaktors have a deviceFlavor of 06.  Is it posible for you to find the actual model number of the devices so we can find a manual or other documentation. It looks like a new kind of device.

**Comment by lassem** [comment]
I am curious, could you share the xml for the specific device here?

**Comment by SifuDaigo** [comment]
OK, I shared the XML here: 
https://www.codepile.net/raw/2qlmlLX1.xml
Including it here directly would mess up all formatting. 

The product is this one here: 
https://www.busch-jaeger.de/at/online-katalog/produktuebersicht?tx_nlbjproducts_catalog%5Baction%5D=show&tx_nlbjproducts_catalog%5BcatBjeProdukt%5D=8376&tx_nlbjproducts_catalog%5Bcontroller%5D=CatStdArtikel&cHash=a2cc3743e8764940df8071538e6ba18d

Any idea where I could find the actual model number?

**Comment by jheling** [comment]
@SifuDaigo . Since the code for the cover and switch actuator is now function based, did your problem disappear?

**Comment by SifuDaigo** [comment]
Sorry, I haven't updated the integration in a while. Just did - and everything works out of the box! Magical! Thank you so much!
Now I can integrate the lightswitches properly. This is really appreciated!

One last question though: For every device there are now two binary sensors showing up with the same name - some on, some off. Can you tell me what those mean?

**Comment by jheling** [comment]
No , this this time the thanks go to @Tho85  who has rewritten a big part of the code.   The two binary sensors are new to me, I do not see them appearing in my HA session. Do you see them for cover devices?

**Comment by SifuDaigo** [comment]
I see them for all the devices. Like this:

![image](https://user-images.githubusercontent.com/60067109/101982914-77959a80-3c77-11eb-9fc9-16e39eb23858.png)

Some of them are on, some are off. It's not a big issue, but I was just curious.

**Comment by Tho85** [comment]
Closing this issue, since it has been stale for a year now. If the problem still persists, feel free to comment again, and I'll reopen it and have a look.
