### ISSUE TITLE
Problem with covers not being found

### ISSUE THREAD

**Issue by certl** [jheling/freeathome#4]
There was a problem in pfreeathome.py that lead to the component not being able to find the covers in my house connected to Busch Jäger free@home "Sensor/ Jalousieaktor 2/1-fach" with deviceID 1015.

Editing line 512 to `if deviceId == 'B001' or deviceId == '1013' or deviceId == '1015':` fixed that.

I guess the same problem with missing deviceIDs will hit with scenes as well. I don't use the scenes from my free@home in home assistant, but I noticed that some of them are not imported by the freeathome component.

**Comment by jheling** [comment]
Thank you, I have  added the device to the  source.  My installation only contains dimmers actors, switch actors and sensor units.  So i need other users to test the covers etc.  User Foti has tested the cover, in his device list this type did not show up.
