### ISSUE TITLE
Wireless thermostat and 4,3 display thermostat

### ISSUE THREAD

**Issue by Helldin** [jheling/freeathome#42]
Hi
In Ha climate control for wireless thermostat shows state off then its on, and it will not read set_temp from thermostat. And then i try to update any stats in ha it will not change anithing.
For display thermostat it will not read set_temp and curent_temp. and its same ther it till not change

I have add folowing lines in pfreeathome.py
` # thermostat
   if device_id == '1004' or device_id == '9004' or device_id == '1020' or \
   device_id == '2041':
   self.add_thermostat(neighbor, serialnumber, roomnames)`
There 1020 is 4,3 Display thermostat and 2041 is wireless thermostat

Data from HA
Wireless thermostat
```
hvac_modes:
  - heat_cool
  - 'off'
min_temp: 7
max_temp: 35
target_temp_step: 0.5
preset_modes:
  - none
  - eco
current_temperature: 22.5
temperature: null
preset_mode: null
friendly_name: Termostat Badrum
icon: 'mdi:thermometer-lines'
supported_features: 17
```

Display thermostat

```
restored: true
hvac_modes:
  - heat_cool
  - 'off'
min_temp: 7
max_temp: 35
target_temp_step: 0.5
preset_modes:
  - none
  - eco
supported_features: 17
friendly_name: Vassvägen
icon: 'mdi:thermometer-lines'

```

Link to mastermessage https://drive.google.com/open?id=1ry3sCz8CZJjdvkkcbT2ZMcf7LKt45O8S

**Comment by jheling** [comment]
Unfortunately I don't have any thermostat devices in my system. Maybe @lassem has a clue?

**Comment by jheling** [comment]
I have just uploaded a new version with support for the 4.3 display thermostat. Thanks to Nadir for developing and testing.

**Comment by Tho85** [comment]
I believe the issue has been resolved. If not, feel free to comment here, and I'll reopen the issue.
