### ISSUE TITLE
Log Warning - using slower slixmpp.stringprep

### ISSUE THREAD

**Issue by Woll3** [jheling/freeathome#44]
Hello,

i got the following log:
Logger: slixmpp.stringprep
Source: custom_components/freeathome/pfreeathome.py:11
First occurred: 8:04:21 PM (1 occurrences) 
Using slower stringprep, consider compiling the faster cython/libidn one.

Free@Home:
Version: 2.4.0
Revision: 7586

Home Assistant:
Version: 0.108.3
arch: x86_x64

Thanks for your support!
Cheers

**Comment by jheling** [comment]
Hello, This is a warning.  This is not a indication that the free@home is not working. So you can ignore it ;-).
