### ISSUE TITLE
settings.py using undefined 'log'

### ISSUE THREAD

**Issue by bartdorlandt** [jheling/freeathome#46]
Just wanted to check with the developers:
file: "freeathome/fah/settings.py"

it is using "log", while it is not defined in this file.
It is actually defined in the "get-master-message.py", where the class in settings.py is imported.

Just wanted to check if this is actually allowed, or if it should include:

`import logging
log = logging.getLogger(__name__)
`

If you would run 'python get-master-message.py', where the IP address is still "xx.xx.xx.xx" you would see the traceback errors for  'log' being undefined.

They are shown correctly on the screen when the above code is also added to settings.py file.

**Comment by jheling** [comment]
yes, I think the log should be added to the source.  I have updated the repository.
