### ISSUE TITLE
xmpp functionality

### ISSUE THREAD

**Issue by lassem** [jheling/freeathome#5]
Hi!

Reaching out via an Issue since there doesn't seem to be a better way.

I have added support for Free@Home thermostats; or partially at least.
I can't get the updates coming back from the sysap.
I've had it working before in https://github.com/lassem/freeAtHomeNibeLink and we also got it working in the openhab addon https://github.com/ruebox/openhab2-addons

Problem is that I am not very proficient in Python and I haven't used slixmpp before.

Any ideas?

I pushed the incomplete code to https://github.com/lassem/freeathome/pull/1

**Comment by jheling** [comment]
Hello, 
Sorry for the late reaction.
Sometimes I also get the problem that free@home is not sending any information back.
Mostly a reset of the free@home sysap will help for me. 
I will take a look at your code,  maybe i can find something. Unfortunately I don't have the thermostat in my system.

**Comment by jheling** [comment]
Hello Lasse,

I took a look at the changes you made.  I saw some difference  in the start
procedure of the Client class.
You have changed the order of the code and removed the line  self
.send_presence_subscription Maybe this is the reason you don't get any
messages back. In my repository I also have the source
get-master-message.py. This is a standalone program. I use this to retrieve
the big xml with all the free@home devices and also to see if there are
messages coming back from the sysap. These messages appear in the logging
window. While testing this program myself, a minute ago, i noticed that the
status messages were not being send by the sysap. Now the original Free@home
does not get status messages either. Tomorrow i will try to find out if i
can fix it. Best Johan.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op wo 26 dec. 2018 om 19:27 schreef Lasse Magnussen <
notifications@github.com>:

**Comment by jheling** [comment]
Hello Lasse,
Did you manage to get the state messages of the thermostat working?
Best, Johan

**Comment by lassem** [comment]
Have been on vacation. I will get back to you on this. I got the thermostats sending updates back via XMPP, but have yet to wire up the needed calls to HA.

**Comment by lassem** [comment]
I have updated PR (https://github.com/lassem/freeathome/pull/1).
Still some things that needs a bit of work; when thermostats are off they report 35 deg. celsius f.ex.

But on a general note, the HASS UI doesn't update when turning on/off lights or adjusting the thermostats.
I suspect there's some HASS state stuff that's missing, but I haven't had the time to look too much into it. Also, I really suck at Python so things are moving slowly.

It would've been great to finalize the component and maybe get it into the official distribution.

Let me know if you need my help. My Free@Home setup has quite a few components. No weather station though.

**Comment by jheling** [comment]
Hello Lasse, can you send me your email adress? 
You can reach me with 'helingj'  on google mail.
I want to show you how 'get-master-message.py' works on my free@home system

**Comment by lassem** [comment]
Closing as issue has been resolved.
