### ISSUE TITLE
Invalid config for [freeathome] required key not provided @ data

### ISSUE THREAD

**Issue by Zyro16** [jheling/freeathome#52]
Hello,

I use Hass.io for Home Assistant. 
I followed the "read me" file but during the config of configuration.yaml I got following error:

**_ERROR (MainThread) [homeassistant.components.hassio] Invalid config for [freeathome]: required key not provided @ data['freeathome']['host']. Got None. (See ?, line ?). 
Component error: password - Integration 'password' not found.
Component error: host - Integration 'host' not found.
Component error: username - Integration 'username' not found._**

Used latest version 2.5.0 
Home Assistant 0.109.3

configuration.yaml:

```
> # Configure a default setup of Home Assistant (frontend, api, etc)
> default_config:
> # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
> # http:
> #   base_url: example.duckdns.org:8123
> 
> # Text to speech
> tts:
>   - platform: google_translate
> 
> freeathome:
> host: 192.168.178.21
> username: admin
> password: xxxx
> 
> group: !include groups.yaml
> automation: !include automations.yaml
> script: !include scripts.yaml
> scene: !include scenes.yaml
```

Can you please help!?

Thank you,
kind regards!
Daniel

**Comment by jheling** [comment]
Hello Daniel,  You have to indent the host, username and password lines by 2 spaces.  Then they will be recognised as parameters of freeathome.

**Comment by Zyro16** [comment]
Thank you very much! @jheling
