### ISSUE TITLE
Problems with install

### ISSUE THREAD

**Issue by mrVoltrix** [jheling/freeathome#54]
Hello, 

I'm complete new with homeassistant I have free@home in my house in Belgium, 
now I tried to install this like on the readme file, but after restarting i get: 

Logger: homeassistant.setup
Source: setup.py:104
First occurred: 22:19:38 (1 occurrences)
Last logged: 22:19:38

Setup failed for freeathome: Integration not found.

What i'm doing wrong? 

Mvg,

**Comment by jheling** [comment]
Hello, Did you put the sources from github in a custom_components folder? The freeathome folder should be in this custom_components folder. The freeathome folder should contain the fah folder.

**Comment by mrVoltrix** [comment]
Hi, 

Yes I put everything in the /config/custom_components folder. Also the fah folder

Verzonden vanuit Mail voor Windows 10

Van: jheling
Verzonden: woensdag 6 mei 2020 6:58
Aan: jheling/freeathome
CC: mrVoltrix; Author
Onderwerp: Re: [jheling/freeathome] Problems with install (#54)

Hello, Did you put the sources from github in a custom_components folder? The freeathome folder should be in this custom_components folder. The freeathome folder should contain the fah folder.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by jheling** [comment]
Can you share your configuration.yaml?

**Comment by mrVoltrix** [comment]
Yes offcourse, 

Thanks for the help!
I’m new with this system so I has to learn a lot I guess

Verzonden vanuit Mail voor Windows 10

Van: jheling
Verzonden: woensdag 6 mei 2020 9:47
Aan: jheling/freeathome
CC: mrVoltrix; Author
Onderwerp: Re: [jheling/freeathome] Problems with install (#54)

Can you share your configuration.yaml?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by jheling** [comment]
Did you manage to get it working?

**Comment by mrVoltrix** [comment]
Yes, When I put my ip adres from the system acces point in de configuration.Yaml it doesn't work but if I write Sysap.home it works. For the moment I only tested my lights and covers. And this works great! Thanks-------- Oorspronkelijk bericht --------Van: jheling <notifications@github.com>Datum: wo 13 mei 2020 06:57Aan: jheling/freeathome <freeathome@noreply.github.com>Cc: mrVoltrix <ruben.florquin@telenet.be>, Author <author@noreply.github.com>Onderwerp: Re: [jheling/freeathome] Problems with install (#54)
Did you manage to get it working?
