### ISSUE TITLE
wireless thermostat are missing in HA

### ISSUE THREAD

**Issue by Zyro16** [jheling/freeathome#56]
Hello,

I installed the awesome tool and also got the Scenes and Lights from the Busch Jaeger System.
But I miss the wireless thermostat. 

I have changed the temperature and I have already turned a thermostat off and on again. Unfortunately it is not displayed as an entity.

Is it necessary to add them manually in the config? If so, how?

Thank you very much for your great work!

Best regards,
Daniel

**Comment by jheling** [comment]
Hello Daniel, This is probably one of the devices that is not supported yet.  I don't have any thermostat devices so I need input from other users  to get this device working.

**Comment by Zyro16** [comment]
Okay, and how can I help? :)
What do you need?

**Comment by dbrouwer1979** [comment]
Hi Daniel, I have the wireless thermostats working. I will sent you the added line later tonight

**Comment by dbrouwer1979** [comment]
I have the following lines in pfreeathome.py (lines 931 to 933):
                # thermostat
                if device_id == '1004' or device_id == '9004' or device_id == '2041':
                    self.add_thermostat(neighbor, serialnumber, roomnames)

Device id 2041 is the wireless thermostat.

Let me know if it works for you!

**Comment by Zyro16** [comment]
Hi dbrouwer1979,

thank you very much!
But it's not working.  HA says, that the config is not valid.

Here is my config. Can you find the failure?

>  def add_thermostat(self, xmlroot, serialnumber, roomnames):
>         """ Add a thermostat to the list of thermostat devices """
>         button_basename = get_attribute(xmlroot, 'displayName')
>         floor_id = get_attribute(xmlroot, 'floor')
>         room_id = get_attribute(xmlroot, 'room')
>         # thermostat
>         if device_id == '1004' or device_id == '9004' or device_id == '2041':
>            self.add_thermostat(neighbor, serialnumber, roomnames)    
>         button_device = serialnumber + '/' + 'ch0000'
>         if floor_id != '' and room_id != '' and self.use_room_names:
>             button_name = button_basename + ' (' + roomnames[floor_id][room_id] + ')'
>         else:
>             button_name = button_basename
> 
>         channels = xmlroot.find('channels')
>         if channels is not None:
>             for channel in channels.findall('channel'):
>                 target_temperature = get_output_datapoint(channel, 'odp0006')
>                 current_temperature = get_output_datapoint(channel, 'odp0010')
>                 state = get_output_datapoint(channel, 'odp0008')
>                 eco_mode = get_output_datapoint(channel, 'odp0009')
> 
>         self.thermostat_devices[button_device] = FahThermostat(self, button_device, button_name,
>                                                                temperature=current_temperature,
>                                                                target=target_temperature,
>                                                                state=state,
>                                                                eco_mode=eco_mode)
>         LOG.info('thermostat %s %s ', button_device, button_name)
> 
>     def add_thermostatdisp(self, xmlroot, serialnumber, roomnames):
>         """ Add a thermostat to the list of thermostat devices """
>         thermostat_basename = get_attribute(xmlroot, 'displayName')
>         floor_id = get_attribute(xmlroot, 'floor')
>         room_id = get_attribute(xmlroot, 'room')

Thank you,
kind regards!

Daniel

**Comment by dbrouwer1979** [comment]
I do not see an error. Do you have the wireless room thermostats or the wireless radiator thermostats?

**Comment by Zyro16** [comment]
I have the wireless radiator thermostats.
Model: 6256/2-WL

The Thermostat is not available as an entity or something else.

**Comment by dbrouwer1979** [comment]
I gave you the device id for the room thermostats. The device id for the radiator thermostats is 2043.
But I must say, these devices are not supported (yet).
I have my radiator thermostats linked to a wireless room thermostat so therefore I don't need the radiator thermostats in HA.

**Comment by Zyro16** [comment]
Thank you very much! 
I don´t have any wireless room thermostat, so this solution will not work for me.
Hope the device will supported at the feature :)

**Comment by dbrouwer1979** [comment]
I am wondering how your radiator thermostats communicate with your heater, can you contact me on my google mail? dbrouwer1979

**Comment by Zyro16** [comment]
sorry for my late reply... you've got mail
Many thanks in advance for your efforts!

**Comment by Zyro16** [comment]
Now it works! Many Thanks to dbrouwer1979 for your help!!!
I added the lines here and added the device_id **2043**

<img width="890" alt="image" src="https://user-images.githubusercontent.com/64769691/81782796-a5a4d780-94fa-11ea-992c-2f2b4c7b5dca.png">

**Comment by dbrouwer1979** [comment]
@jheling I have included the WL room thermostats by adding device_id == 2041 to pfreeathome.py
I noticed that these Wireless thermostats do not respond to actions in HA (turning off/on, etc, does not work)
I know you don't have any thermostats, but what would you need from my end to get these thermostats integrated in the component?

Regard,
Daniel

**Comment by jheling** [comment]
This component will probably use other datapoints than the current thermostat. User Nadir made a FahThermostatDisp where you can see that it also uses other datapoints. You should use get-master-message.py to intercept the messages from the sysapp when you an action on the thermostat with the official FAH app. 
The actions should be: 
- Turn on thermostat
- Turn off thermostat
- Turn eco mode on
- set a new target temperature
These message will probably contain a input datapoint like 'idp0011'.

The thermostat will also send out status message like the current room temperature.  These contain output datapoints like 'odp0006'.  The following datapoints are processed in update_thermostat:
- Target temperatur
- Thermostat on/off
- Thermostat eco mode
- Current temperature
- Actuater state (heat on/off)

**Comment by jheling** [comment]
@Zyro16 with the changes Tho85 made to the thermostat component I assume your wireless thermostats are now visible and working. Can I close this issue?

**Comment by Zyro16** [comment]
Yes, thank you! Now it works perfect!!! Great job
