### ISSUE TITLE
Dimmer Light Control

### ISSUE THREAD

**Issue by dvorpahl** [jheling/freeathome#63]
Hi @jheling,

what about the dimmer component? any ideas or planed for future release? exactly i mean "Dimmaktor 6-fach"

**Comment by jheling** [comment]
Hello, I do not have any plans for the dimmer component.  Thermostats are now my points of interest.
Maybe adding the device id of the 'Dimmaktor 6-fach' could do the trick. I have the 4-fach version in my system.
Can you try to get the get-master-message.py running? This will give you a xml file with all the devices in your system.

**Comment by dvorpahl** [comment]
> Can you try to get the get-master-message.py running? This will give you a xml file with all the devices in your system.

Hi, the current get-master-message.py does not run with sysap v2.5.3. can you help me? i don't know very much about python.

**Comment by jheling** [comment]
Did you get any error messages?

**Comment by dvorpahl** [comment]
> Did you get any error messages?

```
Traceback (most recent call last):
  File "get-master-message.py", line 348, in <module>
    main()
  File "get-master-message.py", line 333, in main
    if version.parse(fahversion) >= version.parse("2.3.0"):
  File "/usr/local/lib/python3.7/dist-packages/packaging/version.py", line 56, in parse
    return Version(version)
  File "/usr/local/lib/python3.7/dist-packages/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

**Comment by jheling** [comment]
If you look at the bottom of the get-master-message.py you wil see 3 variables (ipadress, username and password). They have to be filled in to get the programm working.

**Comment by dvorpahl** [comment]
hi again,
i filled in the values and added extra logging line ... then i found out the fahversion variable is filled with 'None', i replaced hardcoded with the version of my sysap "fahversion = '2.5.2'" .. now i'll get following output. maybe there is something wrong with my python env? i used debian 10.4 to install homeassistant standalone, not the hassio distro.

```
INFO      192.168.1.247 Installer 12345
Traceback (most recent call last):
  File "get-master-message.py", line 351, in <module>
    main()
  File "get-master-message.py", line 337, in main
    iterations, salt = settings.get_scram_settings(username, 'SCRAM-SHA-256')
TypeError: cannot unpack non-iterable NoneType object

```

**Comment by dvorpahl** [comment]
now i've tested the hassio env... same issue

**Comment by dvorpahl** [comment]
#64 will close this issue
