### ISSUE TITLE
Free@Home do not surface in automations

### ISSUE THREAD

**Issue by williamvz** [jheling/freeathome#67]
Just not sure if this is a bug or if this is (currently) nog supported but none of the F@H items surface when I try to create new automations in HA. Any thoughts?

**Comment by jheling** [comment]
I'm sorry but I do not understand the question.  Can you give some examples? The automations part of HA is one of the parts I am not yet using.

**Comment by williamvz** [comment]
The scenario I was thinking of is to have a F@H device do something if a trigger went off. Ideally, I'd make an Ikea Tradfri sensor work with F@H switch/light. 

The image below shows you a scenario where a socket is turned off the moment I start charging my car (just an example). However, none of the F@H items appear either under triggers or under actions. 
![image](https://user-images.githubusercontent.com/37240069/90731489-0c8c1680-e2ca-11ea-839e-060703a47602.png)

**Comment by jheling** [comment]
Now I see what you mean.  The FAH component is not showing up as a device.  
Or should the FAH component be visible as integration plaform and the FAH actuators/sensors should be treated as devices?
I think the latter sounds much better. But it will probably be not a quick fix, i have to dig through the HA documentation.

**Comment by miezie** [comment]
This just works. Please deepen your knowledge on Home Assistant inner workings and potential other solutions. See screenshot:
<img width="1197" alt="Screenshot 2020-08-20 at 13 08 08" src="https://user-images.githubusercontent.com/1294988/90763114-6ef31000-e2e6-11ea-9eb6-583ad39d7973.png">

**Comment by miezie** [comment]
> Or should the FAH component be visible as integration plaform and the FAH actuators/sensors should be treated as devices?

This is a good improvement! But not necessary for this issue. This paves the way (I think) in making it a official component...

**Comment by williamvz** [comment]
Frankly, I just looked for the easiest way possible, which seemed to be Automations. Thanks for letting me know I'm lost. I found the page and will see if I can find the exit to the forest. :-)
