### ISSUE TITLE
Error while setting up freeathome platform for light

### ISSUE THREAD

**Issue by gammaLx** [jheling/freeathome#68]
Hey,

i have home assistant running in a vm. It is currently running on Home Assistant Core 0.112.4. There is an update available to version 0.114.4

Every attempt to update runs into the following error

> 2020-09-14 16:48:57 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for freeathome which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
> 2020-09-14 16:48:58 WARNING (MainThread) [slixmpp.stringprep] Using slower stringprep, consider compiling the faster cython/libidn one.
> 2020-09-14 16:48:59 WARNING (MainThread) [slixmpp.basexmpp] jid property deprecated. Use boundjid.bare
> 2020-09-14 16:49:02 ERROR (MainThread) [homeassistant.components.light] Error while setting up freeathome platform for light
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
>     await asyncio.gather(*pending)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 425, in _async_add_entity
>     raise HomeAssistantError(f"Invalid entity id: {entity.entity_id}")
> homeassistant.exceptions.HomeAssistantError: Invalid entity id: light.
> 2020-09-14 16:49:05 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback async_setup_entity_restore.<locals>._write_unavailable_states(<Event homeassistant_start[L]>) at /usr/src/homeassistant/homeassistant/helpers/entity_registry.py:562
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
>     self._context.run(self._callback, *self._args)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 594, in _write_unavailable_states
>     states.async_set(entry.entity_id, STATE_UNAVAILABLE, attrs)
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1007, in async_set
>     state = State(entity_id, new_state, attributes, last_changed, None, context)
>   File "/usr/src/homeassistant/homeassistant/core.py", line 749, in __init__
>     f"Invalid entity id encountered: {entity_id}. "
> homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: light.. Format should be <domain>.<object_id>

I cannot quite find the source of this problem. Is it really a formatting issue with the initiation of light sources as indicated by <domain>.<object_id> in the last line?
Any tip where to look for solutions?

**Comment by jheling** [comment]
If you look at the list of entities (under configuration, entities), can you see any odd entities? Normally a light devices should start with 'light.'  and end with the name of the device. Maybe there is one without a name.

**Comment by gammaLx** [comment]
Yes, that should be it. There is a device with an id = "light." and name = "not available". I dont know where it originates from. All my lights are listed correctly. There is none missing. I will try to remove it...

Thanks a lot!
