### ISSUE TITLE
Not working 0.88

### ISSUE THREAD

**Issue by dbrouwer1979** [jheling/freeathome#7]
Im getting an error since update to 0.88 with this component. Error relates to unable to install slimpp and to structure of the custom component setup. Anyone solve this?
Im on hassio

**Comment by kaisten** [comment]
I have fixed it for myself by bumping the slimpp version and created a pull request. I haven't made any changes on the structure

**Comment by jheling** [comment]
Thank you for fixing. After the update from  0.86.1 to 0.88.1 I noticed the error in the logging.  I have merged the pull request.

**Comment by dbrouwer1979** [comment]
Thank you for the fix! It works again!
