### ISSUE TITLE
HACS integration?

### ISSUE THREAD

**Issue by miezie** [jheling/freeathome#72]
Would it make sense to integrate with HACS for the main contributors? Let me fix that then.. easy updating for users. Less hazzle then making an official component...

**Comment by Tho85** [comment]
I'd rather go for an official component. It's not that much of a hassle, we just have to split up the HA-specific parts and the parts communicating via XMPP (we already have that in the `fah` subfolder), clean up code and add tests for the former, and publish the latter to pip. It's doable, so maybe we should give it a try.

**Comment by miezie** [comment]
Agree, seems like more efficient. But in the end I think hacs is easier and it reaches the same goal. Although I do think that fah belongs to the official components :)

**Comment by miezie** [comment]
Bad idea, official component is better: closing this one.
