### ISSUE TITLE
Dimmaktor 6-fach (DA/M.210.2.11)  is not showing all entities

### ISSUE THREAD

**Issue by TribunMaximus** [jheling/freeathome#78]
Hi there, 

I'm facing a curios problem and hope someone can help me to solve it.

I'm using a Dimmaktor 6-fach (ABB7013A2BBE) which acts with the following entities:

Küche Dimm (ABB7F592C62F)
Schlafzimmer Dimm Licht (ABB7F592C635)
Kinderzimmer Beleuchtung (ABB700DA7C11)
Wohnzimmer Dimm Licht (ABB7F592C651)
Wohnzimmer Beleuchtung Wohnwand (ABB7F592C659)
Terrasse Dimm (ABB7F593DFC1)

The first four are detected and working correct. But the last both are not visible in HA after import.
I checked the attached config file and if I'm right the pairing from actor to sensors is correct for all 6.
Does anyone know, what I can do to solve this problem?

Many thanks for your help and this outstanding project.

[There are the config files](https://we.tl/t-6N6Ov00MGC)

Br
Jens

**Comment by Tho85** [comment]
Thanks for providing your config file. I've looked into the issue, and it is actually a bug in the code w.r.t. channel mask filtering. The last two devices are erroneously filtered. I'm working on a fix right now.

**Comment by Tho85** [comment]
I've added a possible fix in #79, could you try the code? You can also find it here: https://github.com/Tho85/freeathome/tree/Tho85/add-device-channel-selector

If it works, could you also check if your device with serial number ABB700CB2F11 (Terrasse Steckdose) works as expected? Does the control element (binary sensor) show up for this device? There seems to be a second binary sensor ("Nebenstelle 1"), that will probably be filtered out. Do you know what this is? Could you attach a screenshot of the device's configuration?

**Comment by TribunMaximus** [comment]
@Tho85 thanks for your fast support. 
I've checked Dimmaktor 6-fach (ABB7013A2BBE) and all assigned devices are working fine now. So I think this problem is solved.
As you expected ABB700CB2F11 (Terrasse Steckdose) is not working as expected. The Sensor ist [this product](https://www.busch-jaeger.de/produktuebersicht?tx_nlbjproducts_catalog%5Baction%5D=show&tx_nlbjproducts_catalog%5BcatBjeProdukt%5D=3662&tx_nlbjproducts_catalog%5BcatStdArtikel%5D=3881&tx_nlbjproducts_catalog%5Bcontroller%5D=CatStdArtikel&cHash=ebcad9dad5b89b52623522647e2f3c56).
Screenshots how the sensor appears in HA und BJ can be [found here](https://we.tl/t-zUtUHMtgM9)
Could you also provide a solution for this problem?
Many thanks for you fast help and your work on this outstandig project.

Br
Jens

**Comment by Tho85** [comment]
@TribunMaximus There seems to be only one screenshot from HA, and none from BJ, could you check? And the paste doesn't seem to be complete, I can't find the serial number of the 6-gang dimming actuator. Could you also upload it to some other service, e.g. WeTransfer?

Regarding the sensor device "Terasse Steckdose": Could you check if it behaves correctly, i.e. that "Terasse Steckdose" changes to "on" if you click your switch? (You may have to try several times.)

Regarding the device `light.`: The light does not appear correctly due to naming issues, see #81. TL;DR: Rename your device in BJ from "Ⓐ" to something else, remove the entity in Home Assistant (Settings -> Entities) and restart Home Assistant.

**Comment by TribunMaximus** [comment]
@Tho85: You are right, one screenshot was missing. Please find [here](https://we.tl/t-72CjACZnsm) both pictures.
In both picture we already changed the name of light.
After changing the name the Terasse Steckdosse (ABB700CB2F11) is acting as expected without any errors.
Just to clearify a misunderstanding: Terasse Steckdose (ABB700CB2F11) ist not part of the Dimmaktor 6-fach (ABB7013A2BBE).
Thats the reason why cannnot find the serial number there.

So this issue is solved. Many thanks for your help!
