### ISSUE TITLE
Use Hue lights with two F@H wall switches

### ISSUE THREAD

**Issue by JvD12** [jheling/freeathome#86]
Hi, 

I would like to control a single Hue light with two F@H wall switches. With a single wall switch eveything works fine but with 2 or more the state isn't synchronized between all linked wall switches. I have seen the comment about the Hue emulator: 

"Here's how I control devices in Home Assistant through my in-wall switches: I configured the emulated_hue component, so that Home Assistant works as a Philips Hue bridge, and exposed some lights through it. I then added that Hue bridge to free@home, and the exposed lights showed up in free@home. I can then link my in-wall switches with the virtual Hue light bulbs and control them. Maybe you want to try something similar instead of reading the sensor values directly?"

But I don't understand how to do that. Both the Hue lights and F@H switches are available in Home Assistant. 
Is it an option to write/update the state of a binary sensor with the F@H API?

**Comment by JvD12** [comment]
nobody an idea?

**Comment by Tho85** [comment]
You can configure the `emulated_hue` component to make Home Assistant look like a Philips Hue bridge. This virtual Hue Bridge will then be detected by free@home, and you can drop all lights configured in HA onto your free@home floor plan. It has nothing to do with your existing Hue bridge or the fact that you have actual Philips Hue bulbs; this works for any light that can be controlled by Home Assistant.

Take a look at the [docs](https://www.home-assistant.io/integrations/emulated_hue/) on how to set it up.

**Comment by matteagle1** [comment]
Since updating the SysAP firmware to 3.2.0, the Emulated Hue Integration unfortunately doesn’t work for me anymore. The SysAP no longer recognizes the Emulated Hue. Only the physical Hue Bridge is being detected. Is there a possible solution? Does anyone have the same issue?

**Comment by Tho85** [comment]
According to the release notes of 3.2.0, the SysAP now supports "Hue API version 2". AFAIK `emulated_hue` emulates Hue API version 1. Maybe they dropped support for API version 1 altogether?

I guess there's not much we can do about it, except re-implement `emulated_hue` to emulate API version 2.
