### ISSUE TITLE
More than 70 Free@Home Components

### ISSUE THREAD

**Issue by fahhome123** [jheling/freeathome#89]
Hi

Who have installed more than 70 components at Home.
My Questian is, Should I need a second 6201/640.1 component?

If yes, how I should install this?

**Comment by jheling** [comment]
The system accesspoint 2.0 should support up to 150 wired and wireless devices , but I can't find the max number of devices for the power supply.  Is 70 a problem for you?

**Comment by miezie** [comment]
After going above 25 with Hue I already installed the sysap 2.0. For me it was just so slow. Look at the difference in specs and decide. Installation is easy, create a backup of you current config, replace, boot, do first steps and upload the backup.

**Comment by miezie** [comment]
Maybe ask your supplier? This is not related to the Home Assistant component for Free@home

**Comment by fahhome123** [comment]
if someone has more than 64 Units than a second  6201/640.1 component needed.
