### ISSUE TITLE
thermostat

### ISSUE THREAD

**Issue by dbrouwer1979** [jheling/freeathome#9]
Any progress on getting the thermostat integrated?
I'm willing to help..but not expirienced

**Comment by fotiDim** [comment]
@dbrouwer1979 if you have thermostats at home you can try to capture the logs and post them here.

**Comment by fotiDim** [comment]
@dbrouwer1979 it seems there is a PR https://github.com/jheling/freeathome/issues/5

**Comment by jheling** [comment]
yes, user lassem has written the thermostat part. The code looks good, but he has some issues with the status not coming back from the FAH sysap.  After my vacation i will make a version which will contain a big part of his code, with a few modifications.  @dbrouwer1979 can you send me your mailadress? My adress is helingj at google mail.

**Comment by lassem** [comment]
PR #11 contains a cleaned up version of my code. Take a look and let me know what you thing or if changes are needed.

**Comment by lassem** [comment]
PR #11 has been merged, this issue is resolved. Close?

**Comment by jheling** [comment]
Yes, it is done, thank you
